// Public SAP theme parameters shared by UI5 Web Components and Fundamental NGX.
// Resolve values from the preserved HER palette; never target component internals.
export const SAP_ACCENT_PARAMETERS: Readonly<Record<string, string>> = {
	'--sapLinkColor': '--ef-color-accent-strong',
	'--sapLink_Hover_Color': '--ef-color-accent-strong',
	'--sapLink_Active_Color': '--ef-color-accent-strong',
	'--sapLink_Visited_Color': '--ef-color-accent-strong',
	'--sapButton_TextColor': '--ef-color-accent-strong',
	'--sapButton_IconColor': '--ef-color-accent-strong',
	'--sapButton_Hover_TextColor': '--ef-color-accent-strong',
	'--sapButton_Lite_TextColor': '--ef-color-accent-strong',
	'--sapButton_Lite_Hover_TextColor': '--ef-color-accent-strong',
	'--sapButton_Selected_TextColor': '--ef-color-accent-strong',
	'--sapContent_Selected_TextColor': '--ef-color-accent-strong',
	'--sapContent_Selected_ForegroundColor': '--ef-color-accent-strong',
}

export const SAP_HER_PARAMETERS: Readonly<Record<string, string>> = {
	// Page/header surfaces, including the maintained DynamicPage and Object Page composition.
	'--sapBackgroundColor': '--ef-surface-canvas',
	'--sapBaseColor': '--ef-surface-base',
	'--sapShell_Background': '--ef-shell-surface',
	'--sapShellColor': '--ef-shell-surface',
	'--sapShell_Hover_Background': '--ef-list-hover-surface',
	'--sapShell_Active_Background': '--ef-list-active-surface',
	'--sapShell_Active_TextColor': '--ef-text-strong',
	'--sapShell_SubBrand_TextColor': '--ef-color-accent-strong',
	'--sapGroup_ContentBackground': '--ef-surface-base',
	'--sapGroup_TitleBackground': '--ef-surface-base',
	'--sapObjectHeader_Background': '--ef-object-header-surface',
	'--sapObjectHeader_Hover_Background': '--ef-list-hover-surface',
	'--sapObjectHeader_Title_TextColor': '--ef-text-strong',
	'--sapObjectHeader_Subtitle_TextColor': '--ef-text-muted',
	'--sapObjectHeader_BorderColor': '--ef-border-subtle',
	'--sapPageHeader_Background': '--ef-surface-base',
	'--sapPageFooter_Background': '--ef-surface-base',
	'--sapTile_Background': '--ef-surface-base',
	// Native text, labels and icons inherit the same warm light/dark foregrounds.
	'--sapTextColor': '--ef-text-strong',
	'--sapTitleColor': '--ef-text-strong',
	'--sapGroup_TitleTextColor': '--ef-text-strong',
	'--sapPageHeader_TextColor': '--ef-text-strong',
	'--sapPageFooter_TextColor': '--ef-text-strong',
	'--sapShell_TextColor': '--ef-text-strong',
	'--sapShell_InteractiveTextColor': '--ef-text-strong',
	'--sapContent_ForegroundTextColor': '--ef-text-strong',
	'--sapContent_LabelColor': '--ef-text-muted',
	'--sapContent_IconColor': '--ef-text-muted',
	'--sapContent_NonInteractiveIconColor': '--ef-text-muted',
	'--sapContent_ForegroundColor': '--ef-surface-accent',
	'--sapContent_ForegroundBorderColor': '--ef-border-subtle',
	'--sapContent_Selected_Background': '--ef-surface-accent',
	// Inputs retain native focus/validation behavior while adopting HER surfaces.
	'--sapField_Background': '--ef-control-surface',
	'--sapField_Focus_Background': '--ef-control-surface',
	'--sapField_ReadOnly_Background': '--ef-control-surface',
	'--sapField_Hover_Background': '--ef-list-hover-surface',
	'--sapField_TextColor': '--ef-text-strong',
	'--sapField_PlaceholderTextColor': '--ef-text-muted',
	'--sapField_BorderColor': '--ef-border-subtle',
	'--sapField_ReadOnly_BorderColor': '--ef-border-subtle',
	'--sapField_Hover_BorderColor': '--ef-color-accent-strong',
	// Lists, tables and tabs use public selection and border parameters.
	'--sapList_Background': '--ef-surface-base',
	'--sapList_HeaderBackground': '--ef-surface-base',
	'--sapList_TextColor': '--ef-text-strong',
	'--sapList_HeaderTextColor': '--ef-text-strong',
	'--sapList_BorderColor': '--ef-border-subtle',
	'--sapList_HeaderBorderColor': '--ef-border-subtle',
	'--sapList_Hover_Background': '--ef-list-hover-surface',
	'--sapList_SelectionBackgroundColor': '--ef-list-active-surface',
	'--sapList_Hover_SelectionBackground': '--ef-list-active-surface',
	'--sapList_SelectionBorderColor': '--ef-color-accent-strong',
	'--sapGroup_TitleBorderColor': '--ef-border-subtle',
	'--sapGroup_ContentBorderColor': '--ef-border-subtle',
	'--sapPageHeader_BorderColor': '--ef-border-subtle',
	'--sapPageFooter_BorderColor': '--ef-border-subtle',
	// Ordinary actions must not remain blue/white beside an HER emphasized action.
	'--sapButton_Background': '--ef-control-surface',
	'--sapButton_BorderColor': '--ef-border-subtle',
	'--sapButton_Hover_Background': '--ef-list-hover-surface',
	'--sapButton_Hover_BorderColor': '--ef-color-accent-strong',
	'--sapButton_Lite_Hover_Background': '--ef-list-hover-surface',
	'--sapButton_Selected_Background': '--ef-list-active-surface',
	'--sapButton_Selected_BorderColor': '--ef-color-accent-strong',
	'--sapButton_Selected_Hover_Background': '--ef-list-active-surface',
	'--sapButton_Selected_Hover_BorderColor': '--ef-color-accent-strong',
	// The default native avatar color and feedback use the supplied semantic palette.
	'--sapAvatar_6_Background': '--ef-surface-accent',
	'--sapAvatar_6_TextColor': '--ef-color-accent-strong',
	'--sapAvatar_6_BorderColor': '--ef-border-subtle',
	'--sapNeutralBackground': '--ef-status-neutral-surface',
	'--sapNeutralBorderColor': '--ef-status-neutral-border',
	'--sapNeutralColor': '--ef-status-neutral-text',
	'--sapNeutralTextColor': '--ef-status-neutral-text',
	'--sapSuccessBackground': '--ef-status-positive-surface',
	'--sapSuccessBorderColor': '--ef-status-positive-border',
	'--sapPositiveColor': '--ef-status-positive-text',
	'--sapPositiveTextColor': '--ef-status-positive-text',
	'--sapPositiveElementColor': '--ef-status-positive-text',
	'--sapWarningBackground': '--ef-status-critical-surface',
	'--sapWarningBorderColor': '--ef-status-critical-border',
	'--sapCriticalColor': '--ef-status-critical-text',
	'--sapCriticalTextColor': '--ef-status-critical-text',
	'--sapCriticalElementColor': '--ef-status-critical-text',
	'--sapErrorBackground': '--ef-status-negative-surface',
	'--sapErrorBorderColor': '--ef-status-negative-border',
	'--sapNegativeColor': '--ef-status-negative-text',
	'--sapNegativeTextColor': '--ef-status-negative-text',
	'--sapNegativeElementColor': '--ef-status-negative-text',
	'--sapInformationBackground': '--ef-status-information-surface',
	'--sapInformationBorderColor': '--ef-status-information-border',
	'--sapInformativeColor': '--ef-status-information-text',
	'--sapInformativeTextColor': '--ef-status-information-text',
	'--sapInformativeElementColor': '--ef-status-information-text',
}
