// Generated from current canonical HCM catalogue JSON. Run pnpm hcm:catalogue:generate; do not edit.
import type { HcmCatalogue } from './hcm-catalogue'
export const HCM_CATALOGUE: HcmCatalogue = {
	apps: [
		{
			appCode: 'ACCESS_ASSIGNMENTS',
			title: 'Access Assignments',
			domain: 'access-control',
			catalogueIds: ['tenant-administration'],
			route: '/access-control/access-assignments',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ACCESS_ASSIGNMENTS.discover',
				entitlement: 'hcm.access-control',
			},
		},
		{
			appCode: 'ACTIVE_SESSIONS',
			title: 'Active Sessions',
			domain: 'identity-access',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ACTIVE_SESSIONS.discover',
				entitlement: 'hcm.identity-access',
			},
		},
		{
			appCode: 'ALUMNI_MANAGEMENT',
			title: 'Alumni Management',
			domain: 'offboarding',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ALUMNI_MANAGEMENT.discover',
				entitlement: 'hcm.offboarding',
			},
		},
		{
			appCode: 'ANNOUNCEMENTS',
			title: 'Announcements',
			domain: 'engagement',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ANNOUNCEMENTS.discover',
				entitlement: 'hcm.engagement',
			},
		},
		{
			appCode: 'ANNOUNCEMENT_MANAGEMENT',
			title: 'Announcement Management',
			domain: 'engagement',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ANNOUNCEMENT_MANAGEMENT.discover',
				entitlement: 'hcm.engagement',
			},
		},
		{
			appCode: 'API_CREDENTIALS',
			title: 'API Credentials',
			domain: 'identity-access',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.API_CREDENTIALS.discover',
				entitlement: 'hcm.identity-access',
			},
		},
		{
			appCode: 'APPLY_LEAVE',
			title: 'Apply Leave',
			domain: 'leave',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.APPLY_LEAVE.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'APPROVE_ATTENDANCE',
			title: 'Approve Attendance',
			domain: 'attendance',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.APPROVE_ATTENDANCE.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'APPROVE_EXPENSES',
			title: 'Approve Expenses',
			domain: 'expenses',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.APPROVE_EXPENSES.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'APPROVE_LEAVES',
			title: 'Approve Leaves',
			domain: 'leave',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.APPROVE_LEAVES.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'APPROVE_TIMESHEETS',
			title: 'Approve Timesheets',
			domain: 'timesheet',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.APPROVE_TIMESHEETS.discover',
				entitlement: 'hcm.timesheet',
			},
		},
		{
			appCode: 'APP_CATALOGUE_CONFIGURATION',
			title: 'App Catalogue Configuration',
			domain: 'access-control',
			catalogueIds: ['tenant-administration'],
			route: '/access-control/app-catalogue-configuration',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.APP_CATALOGUE_CONFIGURATION.discover',
				entitlement: 'hcm.access-control',
			},
		},
		{
			appCode: 'ASSET_ADMINISTRATION',
			title: 'Asset Administration',
			domain: 'assets',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ASSET_ADMINISTRATION.discover',
				entitlement: 'hcm.assets',
			},
		},
		{
			appCode: 'ASSET_CATEGORIES',
			title: 'Asset Categories',
			domain: 'assets',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ASSET_CATEGORIES.discover',
				entitlement: 'hcm.assets',
			},
		},
		{
			appCode: 'ASSET_MAINTENANCE',
			title: 'Asset Maintenance',
			domain: 'assets',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ASSET_MAINTENANCE.discover',
				entitlement: 'hcm.assets',
			},
		},
		{
			appCode: 'ASSET_UTILIZATION',
			title: 'Asset Utilization',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ASSET_UTILIZATION.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'ASSIGN_PROJECTS',
			title: 'Assign Projects',
			domain: 'projects',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ASSIGN_PROJECTS.discover',
				entitlement: 'hcm.projects',
			},
		},
		{
			appCode: 'ATTENDANCE_CORRECTIONS',
			title: 'Attendance Corrections',
			domain: 'attendance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ATTENDANCE_CORRECTIONS.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'ATTENDANCE_MANAGEMENT',
			title: 'Attendance Management',
			domain: 'attendance',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ATTENDANCE_MANAGEMENT.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'ATTENDANCE_REPORT',
			title: 'Attendance Report',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ATTENDANCE_REPORT.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'ATTRITION_DASHBOARD',
			title: 'Attrition Dashboard',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ATTRITION_DASHBOARD.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'AUDIT_LOG',
			title: 'Audit Log',
			domain: 'audit',
			catalogueIds: ['tenant-administration'],
			route: '/audit/audit-log',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: { permission: 'hcm.catalogue.AUDIT_LOG.discover', entitlement: 'hcm.audit' },
		},
		{
			appCode: 'BACKGROUND_CHECKS',
			title: 'Background Checks',
			domain: 'recruitment',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.BACKGROUND_CHECKS.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'BENEFITS_COST_ANALYSIS',
			title: 'Benefits Cost Analysis',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.BENEFITS_COST_ANALYSIS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'BENEFIT_CATALOGUE',
			title: 'Benefit Catalogue',
			domain: 'compensation-benefits',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.BENEFIT_CATALOGUE.discover',
				entitlement: 'hcm.compensation-benefits',
			},
		},
		{
			appCode: 'BENEFIT_PROGRAMS',
			title: 'Benefit Programs',
			domain: 'compensation-benefits',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.BENEFIT_PROGRAMS.discover',
				entitlement: 'hcm.compensation-benefits',
			},
		},
		{
			appCode: 'CANDIDATE_PIPELINE',
			title: 'Candidate Pipeline',
			domain: 'recruitment',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.CANDIDATE_PIPELINE.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'CLIENT_MANAGEMENT',
			title: 'Client Management',
			domain: 'projects',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.CLIENT_MANAGEMENT.discover',
				entitlement: 'hcm.projects',
			},
		},
		{
			appCode: 'COMPENSATION_ANALYSIS',
			title: 'Compensation Analysis',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMPENSATION_ANALYSIS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'COMPENSATION_COMPONENTS',
			title: 'Compensation Components',
			domain: 'compensation-benefits',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMPENSATION_COMPONENTS.discover',
				entitlement: 'hcm.compensation-benefits',
			},
		},
		{
			appCode: 'COMPENSATION_CYCLES',
			title: 'Compensation Cycles',
			domain: 'compensation-benefits',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMPENSATION_CYCLES.discover',
				entitlement: 'hcm.compensation-benefits',
			},
		},
		{
			appCode: 'COMPETENCY_CATALOGUE',
			title: 'Competency Catalogue',
			domain: 'skills',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMPETENCY_CATALOGUE.discover',
				entitlement: 'hcm.skills',
			},
		},
		{
			appCode: 'COMPLIANCE_DASHBOARD',
			title: 'Compliance Dashboard',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMPLIANCE_DASHBOARD.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'COMPLIANCE_TRACKING',
			title: 'Compliance Tracking',
			domain: 'governance',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMPLIANCE_TRACKING.discover',
				entitlement: 'hcm.governance',
			},
		},
		{
			appCode: 'COMP_OFF_ADMINISTRATION',
			title: 'Comp Off Administration',
			domain: 'leave',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMP_OFF_ADMINISTRATION.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'COMP_OFF_ENCASHMENT',
			title: 'Comp Off Encashment',
			domain: 'leave',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.COMP_OFF_ENCASHMENT.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'DATA_EXPORT_LOG',
			title: 'Data Export Log',
			domain: 'audit',
			catalogueIds: ['tenant-administration'],
			route: '/audit/data-export-log',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.DATA_EXPORT_LOG.discover',
				entitlement: 'hcm.audit',
			},
		},
		{
			appCode: 'DATA_RIGHTS_REQUESTS',
			title: 'Data Rights Requests',
			domain: 'governance',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.DATA_RIGHTS_REQUESTS.discover',
				entitlement: 'hcm.governance',
			},
		},
		{
			appCode: 'DOCUMENT_REQUESTS',
			title: 'Document Requests',
			domain: 'documents',
			catalogueIds: ['hr-specialist-operations', 'employee-self-service'],
			route: '/documents/document-requests',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.DOCUMENT_REQUESTS.discover',
				entitlement: 'hcm.documents',
			},
		},
		{
			appCode: 'DOCUMENT_TEMPLATES',
			title: 'Document Templates',
			domain: 'documents',
			catalogueIds: ['tenant-administration', 'hr-specialist-operations'],
			route: '/documents/document-templates',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.DOCUMENT_TEMPLATES.discover',
				entitlement: 'hcm.documents',
			},
		},
		{
			appCode: 'DOCUMENT_TYPES',
			title: 'Document Types',
			domain: 'documents',
			catalogueIds: ['tenant-administration', 'hr-specialist-operations'],
			route: '/documents/document-types',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.DOCUMENT_TYPES.discover',
				entitlement: 'hcm.documents',
			},
		},
		{
			appCode: 'DOMAIN_CONFIGURATION',
			title: 'Domain Configuration',
			domain: 'identity-access',
			catalogueIds: ['tenant-administration'],
			route: '/identity-access/domain-configuration',
			floorplan: 'UX-FP-STANDARD-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.DOMAIN_CONFIGURATION.discover',
				entitlement: 'hcm.identity-access',
			},
		},
		{
			appCode: 'EMAIL_SENDER_CONFIGURATION',
			title: 'Email Sender Configuration',
			domain: 'notifications',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMAIL_SENDER_CONFIGURATION.discover',
				entitlement: 'hcm.notifications',
			},
		},
		{
			appCode: 'EMPLOYEE_DIRECTORY',
			title: 'Employee Directory',
			domain: 'employee',
			catalogueIds: ['employee-self-service'],
			route: '/employee/employee-directory',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMPLOYEE_DIRECTORY.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'EMPLOYEE_DOCUMENTS',
			title: 'Employee Documents',
			domain: 'documents',
			catalogueIds: ['hr-specialist-operations'],
			route: '/documents/employee-documents',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMPLOYEE_DOCUMENTS.discover',
				entitlement: 'hcm.documents',
			},
		},
		{
			appCode: 'EMPLOYEE_IMPORT',
			title: 'Employee Import',
			domain: 'employee',
			catalogueIds: ['hr-specialist-operations'],
			route: '/employee/employee-import',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMPLOYEE_IMPORT.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'EMPLOYEE_PROFILE_CONFIGURATION',
			title: 'Employee Profile Configuration',
			domain: 'employee',
			catalogueIds: ['hr-specialist-operations'],
			route: '/employee/employee-profile-configuration',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMPLOYEE_PROFILE_CONFIGURATION.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'EMPLOYEE_RECORDS',
			title: 'Employee Records',
			domain: 'employee',
			catalogueIds: ['hr-specialist-operations'],
			route: '/employee/employee-records',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMPLOYEE_RECORDS.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'EMPLOYEE_REFERRALS',
			title: 'Employee Referrals',
			domain: 'recruitment',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMPLOYEE_REFERRALS.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'EMPLOYMENT_CHANGES',
			title: 'Employment Changes',
			domain: 'employee',
			catalogueIds: ['hr-specialist-operations'],
			route: '/employee/employment-changes',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EMPLOYMENT_CHANGES.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'ENGAGEMENT_SURVEYS',
			title: 'Engagement Surveys',
			domain: 'engagement',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ENGAGEMENT_SURVEYS.discover',
				entitlement: 'hcm.engagement',
			},
		},
		{
			appCode: 'EXPENSE_ADMINISTRATION',
			title: 'Expense Administration',
			domain: 'expenses',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EXPENSE_ADMINISTRATION.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'EXPENSE_ANALYSIS',
			title: 'Expense Analysis',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EXPENSE_ANALYSIS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'EXPENSE_POLICIES',
			title: 'Expense Policies',
			domain: 'expenses',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.EXPENSE_POLICIES.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'FINAL_SETTLEMENTS',
			title: 'Final Settlements',
			domain: 'offboarding',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.FINAL_SETTLEMENTS.discover',
				entitlement: 'hcm.offboarding',
			},
		},
		{
			appCode: 'GIVE_FEEDBACK',
			title: 'Give Feedback',
			domain: 'performance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.GIVE_FEEDBACK.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'GIVE_RECOGNITION',
			title: 'Give Recognition',
			domain: 'engagement',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.GIVE_RECOGNITION.discover',
				entitlement: 'hcm.engagement',
			},
		},
		{
			appCode: 'HEADCOUNT_ANALYSIS',
			title: 'Headcount Analysis',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.HEADCOUNT_ANALYSIS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'HIRING_FUNNEL',
			title: 'Hiring Funnel',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.HIRING_FUNNEL.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'HOLIDAY_CALENDARS',
			title: 'Holiday Calendars',
			domain: 'attendance',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.HOLIDAY_CALENDARS.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'HR_ANALYTICS',
			title: 'HR Analytics',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.HR_ANALYTICS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'HR_SERVICE_DESK',
			title: 'HR Service Desk',
			domain: 'employee',
			catalogueIds: ['hr-specialist-operations'],
			route: '/employee/hr-service-desk',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.HR_SERVICE_DESK.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'IDENTIFICATION_TYPES',
			title: 'Identification Types',
			domain: 'workforce-foundation',
			catalogueIds: ['tenant-administration', 'hr-specialist-operations'],
			route: '/workforce-foundation/identification-types',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.IDENTIFICATION_TYPES.discover',
				entitlement: 'hcm.workforce-foundation',
			},
		},
		{
			appCode: 'IDENTITY_ADMINISTRATION',
			title: 'Identity Administration',
			domain: 'identity-access',
			catalogueIds: ['tenant-administration'],
			route: '/identity-access/identity-administration',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.IDENTITY_ADMINISTRATION.discover',
				entitlement: 'hcm.identity-access',
			},
		},
		{
			appCode: 'INITIATE_PIP',
			title: 'Initiate PIP',
			domain: 'performance',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.INITIATE_PIP.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'INTERVIEW_OPERATIONS',
			title: 'Interview Operations',
			domain: 'recruitment',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.INTERVIEW_OPERATIONS.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'INTERVIEW_PANEL',
			title: 'Interview Panel',
			domain: 'recruitment',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.INTERVIEW_PANEL.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'JOB_CATALOGUE',
			title: 'Job Catalogue',
			domain: 'job-architecture',
			catalogueIds: ['tenant-administration'],
			route: '/job-architecture/job-catalogue',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.JOB_CATALOGUE.discover',
				entitlement: 'hcm.job-architecture',
			},
		},
		{
			appCode: 'JOB_REQUISITIONS',
			title: 'Job Requisitions',
			domain: 'recruitment',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.JOB_REQUISITIONS.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'LEARNING_PATHS',
			title: 'Learning Paths',
			domain: 'learning',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LEARNING_PATHS.discover',
				entitlement: 'hcm.learning',
			},
		},
		{
			appCode: 'LEARNING_PROGRAMS',
			title: 'Learning Programs',
			domain: 'learning',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LEARNING_PROGRAMS.discover',
				entitlement: 'hcm.learning',
			},
		},
		{
			appCode: 'LEAVE_ADMINISTRATION',
			title: 'Leave Administration',
			domain: 'leave',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LEAVE_ADMINISTRATION.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'LEAVE_BALANCE',
			title: 'Leave Balance',
			domain: 'leave',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LEAVE_BALANCE.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'LEAVE_ENCASHMENT',
			title: 'Leave Encashment',
			domain: 'leave',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LEAVE_ENCASHMENT.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'LEAVE_POLICIES',
			title: 'Leave Policies',
			domain: 'leave',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LEAVE_POLICIES.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'LEAVE_TRENDS',
			title: 'Leave Trends',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LEAVE_TRENDS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'LOOKUP_VALUES',
			title: 'Lookup Values',
			domain: 'workforce-foundation',
			catalogueIds: ['tenant-administration', 'hr-specialist-operations'],
			route: '/workforce-foundation/lookup-values',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.LOOKUP_VALUES.discover',
				entitlement: 'hcm.workforce-foundation',
			},
		},
		{
			appCode: 'MY_ACTIVITY',
			title: 'My Activity',
			domain: 'audit',
			catalogueIds: ['employee-self-service'],
			route: '/audit/my-activity',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_ACTIVITY.discover',
				entitlement: 'hcm.audit',
			},
		},
		{
			appCode: 'MY_APPROVALS',
			title: 'My Approvals',
			domain: 'workflow',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_APPROVALS.discover',
				entitlement: 'hcm.workflow',
			},
		},
		{
			appCode: 'MY_ASSETS',
			title: 'My Assets',
			domain: 'assets',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_ASSETS.discover',
				entitlement: 'hcm.assets',
			},
		},
		{
			appCode: 'MY_ATTENDANCE',
			title: 'My Attendance',
			domain: 'attendance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_ATTENDANCE.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'MY_BENEFITS',
			title: 'My Benefits',
			domain: 'compensation-benefits',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_BENEFITS.discover',
				entitlement: 'hcm.compensation-benefits',
			},
		},
		{
			appCode: 'MY_COMPENSATION',
			title: 'My Compensation',
			domain: 'compensation-benefits',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_COMPENSATION.discover',
				entitlement: 'hcm.compensation-benefits',
			},
		},
		{
			appCode: 'MY_DOCUMENTS',
			title: 'My Documents',
			domain: 'documents',
			catalogueIds: ['employee-self-service'],
			route: '/documents/my-documents',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_DOCUMENTS.discover',
				entitlement: 'hcm.documents',
			},
		},
		{
			appCode: 'MY_EXIT',
			title: 'My Exit',
			domain: 'offboarding',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_EXIT.discover',
				entitlement: 'hcm.offboarding',
			},
		},
		{
			appCode: 'MY_EXPENSES',
			title: 'My Expenses',
			domain: 'expenses',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_EXPENSES.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'MY_GOALS',
			title: 'My Goals',
			domain: 'performance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_GOALS.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'MY_HR_REQUESTS',
			title: 'My HR Requests',
			domain: 'employee',
			catalogueIds: ['employee-self-service'],
			route: '/employee/my-hr-requests',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_HR_REQUESTS.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'MY_LEARNING',
			title: 'My Learning',
			domain: 'learning',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_LEARNING.discover',
				entitlement: 'hcm.learning',
			},
		},
		{
			appCode: 'MY_NOTIFICATIONS',
			title: 'My Notifications',
			domain: 'notifications',
			catalogueIds: ['employee-self-service'],
			route: '/notifications/my-notifications',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_NOTIFICATIONS.discover',
				entitlement: 'hcm.notifications',
			},
		},
		{
			appCode: 'MY_NOTIFICATION_PREFERENCES',
			title: 'My Notification Preferences',
			domain: 'notifications',
			catalogueIds: ['employee-self-service'],
			route: '/notifications/my-notification-preferences',
			floorplan: 'UX-FP-STANDARD-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_NOTIFICATION_PREFERENCES.discover',
				entitlement: 'hcm.notifications',
			},
		},
		{
			appCode: 'MY_ONBOARDING',
			title: 'My Onboarding',
			domain: 'onboarding',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_ONBOARDING.discover',
				entitlement: 'hcm.onboarding',
			},
		},
		{
			appCode: 'MY_PAYSLIPS',
			title: 'My Payslips',
			domain: 'payroll',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_PAYSLIPS.discover',
				entitlement: 'hcm.payroll',
			},
		},
		{
			appCode: 'MY_PERFORMANCE',
			title: 'My Performance',
			domain: 'performance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_PERFORMANCE.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'MY_PIP',
			title: 'My PIP',
			domain: 'performance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_PIP.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'MY_PROFILE',
			title: 'My Profile',
			domain: 'employee',
			catalogueIds: ['employee-self-service'],
			route: '/employee/my-profile',
			floorplan: 'UX-FP-OBJECT-PAGE',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_PROFILE.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'MY_PROJECTS',
			title: 'My Projects',
			domain: 'projects',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_PROJECTS.discover',
				entitlement: 'hcm.projects',
			},
		},
		{
			appCode: 'MY_SCHEDULE',
			title: 'My Schedule',
			domain: 'attendance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_SCHEDULE.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'MY_SECURITY',
			title: 'My Security',
			domain: 'identity-access',
			catalogueIds: ['employee-self-service'],
			route: '/identity-access/my-security',
			floorplan: 'UX-FP-STANDARD-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_SECURITY.discover',
				entitlement: 'hcm.identity-access',
			},
		},
		{
			appCode: 'MY_SKILLS',
			title: 'My Skills',
			domain: 'skills',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_SKILLS.discover',
				entitlement: 'hcm.skills',
			},
		},
		{
			appCode: 'MY_TASKS',
			title: 'My Tasks',
			domain: 'workflow',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_TASKS.discover',
				entitlement: 'hcm.workflow',
			},
		},
		{
			appCode: 'MY_TAX_DECLARATIONS',
			title: 'My Tax Declarations',
			domain: 'payroll',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_TAX_DECLARATIONS.discover',
				entitlement: 'hcm.payroll',
			},
		},
		{
			appCode: 'MY_TAX_DOCUMENTS',
			title: 'My Tax Documents',
			domain: 'payroll',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_TAX_DOCUMENTS.discover',
				entitlement: 'hcm.payroll',
			},
		},
		{
			appCode: 'MY_TIMESHEET',
			title: 'My Timesheet',
			domain: 'timesheet',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_TIMESHEET.discover',
				entitlement: 'hcm.timesheet',
			},
		},
		{
			appCode: 'MY_TRAVEL_ADVANCES',
			title: 'My Travel Advances',
			domain: 'expenses',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.MY_TRAVEL_ADVANCES.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'NOTIFICATION_RULES',
			title: 'Notification Rules',
			domain: 'notifications',
			catalogueIds: ['tenant-administration'],
			route: '/notifications/notification-rules',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.NOTIFICATION_RULES.discover',
				entitlement: 'hcm.notifications',
			},
		},
		{
			appCode: 'NOTIFICATION_TEMPLATES',
			title: 'Notification Templates',
			domain: 'notifications',
			catalogueIds: ['tenant-administration'],
			route: '/notifications/notification-templates',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.NOTIFICATION_TEMPLATES.discover',
				entitlement: 'hcm.notifications',
			},
		},
		{
			appCode: 'OFFBOARDING_OPERATIONS',
			title: 'Offboarding Operations',
			domain: 'offboarding',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.OFFBOARDING_OPERATIONS.discover',
				entitlement: 'hcm.offboarding',
			},
		},
		{
			appCode: 'OFFER_MANAGEMENT',
			title: 'Offer Management',
			domain: 'recruitment',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.OFFER_MANAGEMENT.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'ONBOARDING_METRICS',
			title: 'Onboarding Metrics',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ONBOARDING_METRICS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'ONBOARDING_OPERATIONS',
			title: 'Onboarding Operations',
			domain: 'onboarding',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ONBOARDING_OPERATIONS.discover',
				entitlement: 'hcm.onboarding',
			},
		},
		{
			appCode: 'ORG_CHART',
			title: 'Org Chart',
			domain: 'workforce-foundation',
			catalogueIds: ['employee-self-service'],
			route: '/workforce-foundation/org-chart',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ORG_CHART.discover',
				entitlement: 'hcm.workforce-foundation',
			},
		},
		{
			appCode: 'ORGANIZATION_STRUCTURE',
			title: 'Organization Structure',
			domain: 'workforce-foundation',
			catalogueIds: ['tenant-administration', 'hr-specialist-operations'],
			route: '/workforce-foundation/organization-structure',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ORGANIZATION_STRUCTURE.discover',
				entitlement: 'hcm.workforce-foundation',
			},
		},
		{
			appCode: 'OUTBOUND_WEBHOOKS',
			title: 'Outbound Webhooks',
			domain: 'notifications',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.OUTBOUND_WEBHOOKS.discover',
				entitlement: 'hcm.notifications',
			},
		},
		{
			appCode: 'PAYROLL_COMPLIANCE',
			title: 'Payroll Compliance',
			domain: 'payroll',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PAYROLL_COMPLIANCE.discover',
				entitlement: 'hcm.payroll',
			},
		},
		{
			appCode: 'PAYROLL_INPUTS',
			title: 'Payroll Inputs',
			domain: 'payroll',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PAYROLL_INPUTS.discover',
				entitlement: 'hcm.payroll',
			},
		},
		{
			appCode: 'PAYROLL_RUNS',
			title: 'Payroll Runs',
			domain: 'payroll',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PAYROLL_RUNS.discover',
				entitlement: 'hcm.payroll',
			},
		},
		{
			appCode: 'PAYROLL_SUMMARY',
			title: 'Payroll Summary',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PAYROLL_SUMMARY.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'PERFORMANCE_CYCLES',
			title: 'Performance Cycles',
			domain: 'performance',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PERFORMANCE_CYCLES.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'PERFORMANCE_INSIGHTS',
			title: 'Performance Insights',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PERFORMANCE_INSIGHTS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'PERF_REVIEW',
			title: 'Perf Review',
			domain: 'performance',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PERF_REVIEW.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'PIP_MANAGEMENT',
			title: 'PIP Management',
			domain: 'performance',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PIP_MANAGEMENT.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'POLICY_ACKNOWLEDGEMENTS',
			title: 'Policy Acknowledgements',
			domain: 'governance',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.POLICY_ACKNOWLEDGEMENTS.discover',
				entitlement: 'hcm.governance',
			},
		},
		{
			appCode: 'POLICY_MANAGEMENT',
			title: 'Policy Management',
			domain: 'governance',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.POLICY_MANAGEMENT.discover',
				entitlement: 'hcm.governance',
			},
		},
		{
			appCode: 'POSITIONS',
			title: 'Positions',
			domain: 'job-architecture',
			catalogueIds: ['hr-specialist-operations'],
			route: '/job-architecture/positions',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.POSITIONS.discover',
				entitlement: 'hcm.job-architecture',
			},
		},
		{
			appCode: 'POSITION_REQUIREMENTS',
			title: 'Position Requirements',
			domain: 'job-architecture',
			catalogueIds: ['tenant-administration'],
			route: '/job-architecture/position-requirements',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.POSITION_REQUIREMENTS.discover',
				entitlement: 'hcm.job-architecture',
			},
		},
		{
			appCode: 'PROBATION_MANAGEMENT',
			title: 'Probation Management',
			domain: 'employee',
			catalogueIds: ['hr-specialist-operations'],
			route: '/employee/probation-management',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PROBATION_MANAGEMENT.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'PROBATION_REVIEW',
			title: 'Probation Review',
			domain: 'employee',
			catalogueIds: ['manager-self-service'],
			route: '/employee/probation-review',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PROBATION_REVIEW.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'PROJECT_DATA_IMPORT',
			title: 'Project Data Import',
			domain: 'projects',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PROJECT_DATA_IMPORT.discover',
				entitlement: 'hcm.projects',
			},
		},
		{
			appCode: 'PROJECT_MANAGEMENT',
			title: 'Project Management',
			domain: 'projects',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PROJECT_MANAGEMENT.discover',
				entitlement: 'hcm.projects',
			},
		},
		{
			appCode: 'PROJECT_UTILIZATION',
			title: 'Project Utilization',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.PROJECT_UTILIZATION.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'RECOGNITION',
			title: 'Recognition',
			domain: 'engagement',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.RECOGNITION.discover',
				entitlement: 'hcm.engagement',
			},
		},
		{
			appCode: 'RECOGNITION_PROGRAMS',
			title: 'Recognition Programs',
			domain: 'engagement',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.RECOGNITION_PROGRAMS.discover',
				entitlement: 'hcm.engagement',
			},
		},
		{
			appCode: 'REFERENCE_LETTERS',
			title: 'Reference Letters',
			domain: 'offboarding',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.REFERENCE_LETTERS.discover',
				entitlement: 'hcm.offboarding',
			},
		},
		{
			appCode: 'REFERRAL_MANAGEMENT',
			title: 'Referral Management',
			domain: 'recruitment',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.REFERRAL_MANAGEMENT.discover',
				entitlement: 'hcm.recruitment',
			},
		},
		{
			appCode: 'REIMBURSEMENT_RUNS',
			title: 'Reimbursement Runs',
			domain: 'expenses',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.REIMBURSEMENT_RUNS.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'REPORT_BUILDER',
			title: 'Report Builder',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.REPORT_BUILDER.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'RETENTION_POLICIES',
			title: 'Retention Policies',
			domain: 'governance',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.RETENTION_POLICIES.discover',
				entitlement: 'hcm.governance',
			},
		},
		{
			appCode: 'ROLE_MANAGEMENT',
			title: 'Role Management',
			domain: 'access-control',
			catalogueIds: ['tenant-administration'],
			route: '/access-control/role-management',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.ROLE_MANAGEMENT.discover',
				entitlement: 'hcm.access-control',
			},
		},
		{
			appCode: 'SALARY_REVISIONS',
			title: 'Salary Revisions',
			domain: 'compensation-benefits',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SALARY_REVISIONS.discover',
				entitlement: 'hcm.compensation-benefits',
			},
		},
		{
			appCode: 'SECURITY_POLICIES',
			title: 'Security Policies',
			domain: 'identity-access',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SECURITY_POLICIES.discover',
				entitlement: 'hcm.identity-access',
			},
		},
		{
			appCode: 'SENSITIVE_ACCESS_LOG',
			title: 'Sensitive Access Log',
			domain: 'audit',
			catalogueIds: ['tenant-administration'],
			route: '/audit/sensitive-access-log',
			floorplan: 'UX-FP-DYNAMIC-PAGE',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SENSITIVE_ACCESS_LOG.discover',
				entitlement: 'hcm.audit',
			},
		},
		{
			appCode: 'SHIFT_PLANNING',
			title: 'Shift Planning',
			domain: 'attendance',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SHIFT_PLANNING.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'SKILLS_CATALOGUE',
			title: 'Skills Catalogue',
			domain: 'skills',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SKILLS_CATALOGUE.discover',
				entitlement: 'hcm.skills',
			},
		},
		{
			appCode: 'SKILL_GAP_REPORT',
			title: 'Skill Gap Report',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SKILL_GAP_REPORT.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'SSO_CONFIGURATION',
			title: 'SSO Configuration',
			domain: 'identity-access',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SSO_CONFIGURATION.discover',
				entitlement: 'hcm.identity-access',
			},
		},
		{
			appCode: 'SURVEYS',
			title: 'Surveys',
			domain: 'engagement',
			catalogueIds: ['employee-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.SURVEYS.discover',
				entitlement: 'hcm.engagement',
			},
		},
		{
			appCode: 'TASK_TEMPLATES',
			title: 'Task Templates',
			domain: 'onboarding',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TASK_TEMPLATES.discover',
				entitlement: 'hcm.onboarding',
			},
		},
		{
			appCode: 'TAX_DECLARATION_ADMIN',
			title: 'Tax Declaration Admin',
			domain: 'payroll',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TAX_DECLARATION_ADMIN.discover',
				entitlement: 'hcm.payroll',
			},
		},
		{
			appCode: 'TEAM_ATTENDANCE',
			title: 'Team Attendance',
			domain: 'attendance',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_ATTENDANCE.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'TEAM_CALENDAR',
			title: 'Team Calendar',
			domain: 'leave',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_CALENDAR.discover',
				entitlement: 'hcm.leave',
			},
		},
		{
			appCode: 'TEAM_DIRECTORY',
			title: 'Team Directory',
			domain: 'employee',
			catalogueIds: ['manager-self-service'],
			route: '/employee/team-directory',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'planned',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_DIRECTORY.discover',
				entitlement: 'hcm.employee',
			},
		},
		{
			appCode: 'TEAM_EXPENSES',
			title: 'Team Expenses',
			domain: 'expenses',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_EXPENSES.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'TEAM_GOALS',
			title: 'Team Goals',
			domain: 'performance',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_GOALS.discover',
				entitlement: 'hcm.performance',
			},
		},
		{
			appCode: 'TEAM_LEARNING',
			title: 'Team Learning',
			domain: 'learning',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_LEARNING.discover',
				entitlement: 'hcm.learning',
			},
		},
		{
			appCode: 'TEAM_OFFBOARDING',
			title: 'Team Offboarding',
			domain: 'offboarding',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_OFFBOARDING.discover',
				entitlement: 'hcm.offboarding',
			},
		},
		{
			appCode: 'TEAM_ONBOARDING',
			title: 'Team Onboarding',
			domain: 'onboarding',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_ONBOARDING.discover',
				entitlement: 'hcm.onboarding',
			},
		},
		{
			appCode: 'TEAM_SKILLS',
			title: 'Team Skills',
			domain: 'skills',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_SKILLS.discover',
				entitlement: 'hcm.skills',
			},
		},
		{
			appCode: 'TEAM_TIMESHEET',
			title: 'Team Timesheet',
			domain: 'timesheet',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_TIMESHEET.discover',
				entitlement: 'hcm.timesheet',
			},
		},
		{
			appCode: 'TEAM_UTILIZATION',
			title: 'Team Utilization',
			domain: 'projects',
			catalogueIds: ['manager-self-service'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TEAM_UTILIZATION.discover',
				entitlement: 'hcm.projects',
			},
		},
		{
			appCode: 'TENANT_ACCESS_REVIEWS',
			title: 'Tenant Access Reviews',
			domain: 'access-control',
			catalogueIds: ['tenant-administration'],
			route: '/access-control/tenant-access-reviews',
			floorplan: 'UX-FP-FCL',
			implementationStatus: 'complete',
			fddStatus: 'approved',
			tddStatus: 'approved',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TENANT_ACCESS_REVIEWS.discover',
				entitlement: 'hcm.access-control',
			},
		},
		{
			appCode: 'TIMESHEET_ADMINISTRATION',
			title: 'Timesheet Administration',
			domain: 'timesheet',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TIMESHEET_ADMINISTRATION.discover',
				entitlement: 'hcm.timesheet',
			},
		},
		{
			appCode: 'TIMESHEET_COMPLIANCE',
			title: 'Timesheet Compliance',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TIMESHEET_COMPLIANCE.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'TIMESHEET_POLICIES',
			title: 'Timesheet Policies',
			domain: 'timesheet',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TIMESHEET_POLICIES.discover',
				entitlement: 'hcm.timesheet',
			},
		},
		{
			appCode: 'TRAINING_EFFECTIVENESS',
			title: 'Training Effectiveness',
			domain: 'analytics',
			catalogueIds: ['people-analytics'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TRAINING_EFFECTIVENESS.discover',
				entitlement: 'hcm.analytics',
			},
		},
		{
			appCode: 'TRAVEL_ADVANCE_ADMIN',
			title: 'Travel Advance Admin',
			domain: 'expenses',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.TRAVEL_ADVANCE_ADMIN.discover',
				entitlement: 'hcm.expenses',
			},
		},
		{
			appCode: 'UTILIZATION_POLICIES',
			title: 'Utilization Policies',
			domain: 'projects',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.UTILIZATION_POLICIES.discover',
				entitlement: 'hcm.projects',
			},
		},
		{
			appCode: 'WORKFLOW_DEFINITIONS',
			title: 'Workflow Definitions',
			domain: 'workflow',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.WORKFLOW_DEFINITIONS.discover',
				entitlement: 'hcm.workflow',
			},
		},
		{
			appCode: 'WORKFLOW_OPERATIONS',
			title: 'Workflow Operations',
			domain: 'workflow',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.WORKFLOW_OPERATIONS.discover',
				entitlement: 'hcm.workflow',
			},
		},
		{
			appCode: 'WORK_SCHEDULES',
			title: 'Work Schedules',
			domain: 'attendance',
			catalogueIds: ['hr-specialist-operations'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.WORK_SCHEDULES.discover',
				entitlement: 'hcm.attendance',
			},
		},
		{
			appCode: 'WORK_SCHEDULE_TEMPLATES',
			title: 'Work Schedule Templates',
			domain: 'attendance',
			catalogueIds: ['tenant-administration'],
			route: null,
			floorplan: null,
			implementationStatus: 'planned',
			fddStatus: 'not-finalized',
			tddStatus: 'not-finalized',
			discoveryPolicy: {
				permission: 'hcm.catalogue.WORK_SCHEDULE_TEMPLATES.discover',
				entitlement: 'hcm.attendance',
			},
		},
	],
	spaces: [
		{
			spaceId: 'employee',
			title: 'Employee',
			description: 'Personal work, time, pay, growth, lifecycle, and engagement.',
			pageIds: [
				'employee-overview',
				'employee-work-time',
				'employee-pay-benefits',
				'employee-growth',
				'employee-lifecycle',
			],
		},
		{
			spaceId: 'manager',
			title: 'Manager',
			description: 'Team work queues, operations, lifecycle, performance, and development.',
			pageIds: ['manager-overview', 'manager-team-operations', 'manager-development'],
		},
		{
			spaceId: 'hr-operations',
			title: 'HR Operations',
			description: 'Workforce and specialist operational workbenches.',
			pageIds: [
				'hr-workforce',
				'hr-recruitment-lifecycle',
				'hr-time-projects',
				'hr-pay-expenses',
				'hr-talent',
				'hr-governance-assets-engagement',
			],
		},
		{
			spaceId: 'analytics',
			title: 'Analytics',
			description: 'Governed workforce, operations, finance, and talent insights.',
			pageIds: ['analytics-workforce-operations', 'analytics-finance-talent'],
		},
		{
			spaceId: 'tenant-administration',
			title: 'Administration',
			description:
				'Tenant security, access, communication, reference data, assurance, and privacy.',
			pageIds: [
				'admin-identity-access',
				'admin-communication',
				'admin-reference-data',
				'admin-assurance-governance',
			],
		},
	],
	pages: [
		{
			pageId: 'employee-overview',
			title: 'My Overview',
			description: 'High-frequency self-service, work queue, directory, and communication apps.',
			sections: [
				{
					sectionId: 'employee-quick-actions',
					title: 'Quick Actions',
					display: 'tiles',
					appCodes: ['MY_TASKS', 'APPLY_LEAVE', 'MY_TIMESHEET', 'MY_EXPENSES'],
				},
				{
					sectionId: 'employee-information-service',
					title: 'Information and Service',
					display: 'mixed',
					appCodes: [
						'MY_PROFILE',
						'MY_HR_REQUESTS',
						'MY_NOTIFICATIONS',
						'EMPLOYEE_DIRECTORY',
						'ORG_CHART',
						'ANNOUNCEMENTS',
						'MY_ACTIVITY',
						'MY_NOTIFICATION_PREFERENCES',
						'MY_SECURITY',
					],
				},
				{
					sectionId: 'employee-engagement',
					title: 'Engagement',
					display: 'links',
					appCodes: ['SURVEYS', 'RECOGNITION'],
				},
			],
		},
		{
			pageId: 'employee-work-time',
			title: 'Work, Time, Leave, and Expenses',
			description: 'Daily project, time, attendance, leave, expense, and travel work.',
			sections: [
				{
					sectionId: 'employee-work',
					title: 'Work and Time',
					display: 'tiles',
					appCodes: ['MY_PROJECTS', 'MY_TIMESHEET', 'MY_ATTENDANCE', 'MY_SCHEDULE'],
				},
				{
					sectionId: 'employee-time-corrections',
					title: 'Leave and Corrections',
					display: 'tiles',
					appCodes: [
						'ATTENDANCE_CORRECTIONS',
						'APPLY_LEAVE',
						'LEAVE_BALANCE',
						'COMP_OFF_ENCASHMENT',
					],
				},
				{
					sectionId: 'employee-expenses-travel',
					title: 'Expenses and Travel',
					display: 'tiles',
					appCodes: ['MY_EXPENSES', 'MY_TRAVEL_ADVANCES'],
				},
			],
		},
		{
			pageId: 'employee-pay-benefits',
			title: 'Pay and Benefits',
			description: 'Payslips, taxes, compensation, and benefits.',
			sections: [
				{
					sectionId: 'employee-pay',
					title: 'Pay and Tax',
					display: 'tiles',
					appCodes: ['MY_PAYSLIPS', 'MY_TAX_DOCUMENTS', 'MY_TAX_DECLARATIONS'],
				},
				{
					sectionId: 'employee-compensation-benefits',
					title: 'Compensation and Benefits',
					display: 'tiles',
					appCodes: ['MY_COMPENSATION', 'MY_BENEFITS'],
				},
			],
		},
		{
			pageId: 'employee-growth',
			title: 'Learning and Performance',
			description: 'Skills, learning, goals, reviews, improvement plans, and feedback.',
			sections: [
				{
					sectionId: 'employee-learning-skills',
					title: 'Learning and Skills',
					display: 'tiles',
					appCodes: ['MY_SKILLS', 'MY_LEARNING'],
				},
				{
					sectionId: 'employee-performance',
					title: 'Performance',
					display: 'tiles',
					appCodes: ['MY_PERFORMANCE', 'MY_GOALS', 'MY_PIP', 'GIVE_FEEDBACK'],
				},
			],
		},
		{
			pageId: 'employee-lifecycle',
			title: 'Lifecycle and Compliance',
			description:
				'Employment journeys, documents, assets, referrals, and policy acknowledgements.',
			sections: [
				{
					sectionId: 'employee-lifecycle-journeys',
					title: 'Lifecycle',
					display: 'tiles',
					appCodes: ['MY_ONBOARDING', 'MY_EXIT', 'EMPLOYEE_REFERRALS'],
				},
				{
					sectionId: 'employee-documents-compliance',
					title: 'Documents and Compliance',
					display: 'tiles',
					appCodes: ['MY_DOCUMENTS', 'DOCUMENT_REQUESTS', 'POLICY_ACKNOWLEDGEMENTS', 'MY_ASSETS'],
				},
			],
		},
		{
			pageId: 'manager-overview',
			title: 'Team Overview',
			description: 'Manager work queue, team directory, and calendar.',
			sections: [
				{
					sectionId: 'manager-work-queue',
					title: 'Work Queue',
					display: 'tiles',
					appCodes: ['MY_APPROVALS', 'TEAM_DIRECTORY', 'TEAM_CALENDAR'],
				},
				{
					sectionId: 'manager-common-approvals',
					title: 'Common Approvals',
					display: 'tiles',
					appCodes: [
						'APPROVE_LEAVES',
						'APPROVE_ATTENDANCE',
						'APPROVE_TIMESHEETS',
						'APPROVE_EXPENSES',
					],
				},
			],
		},
		{
			pageId: 'manager-team-operations',
			title: 'Team Operations',
			description: 'Team time, projects, expenses, recruitment, onboarding, and offboarding.',
			sections: [
				{
					sectionId: 'manager-time-projects',
					title: 'Time and Projects',
					display: 'tiles',
					appCodes: [
						'TEAM_ATTENDANCE',
						'SHIFT_PLANNING',
						'TEAM_TIMESHEET',
						'TEAM_UTILIZATION',
						'ASSIGN_PROJECTS',
					],
				},
				{
					sectionId: 'manager-expenses',
					title: 'Expenses',
					display: 'links',
					appCodes: ['TEAM_EXPENSES'],
				},
				{
					sectionId: 'manager-lifecycle',
					title: 'Recruitment and Lifecycle',
					display: 'tiles',
					appCodes: ['INTERVIEW_PANEL', 'TEAM_ONBOARDING', 'PROBATION_REVIEW', 'TEAM_OFFBOARDING'],
				},
			],
		},
		{
			pageId: 'manager-development',
			title: 'Performance and Development',
			description: 'Team reviews, goals, improvement, learning, skills, and recognition.',
			sections: [
				{
					sectionId: 'manager-performance',
					title: 'Performance',
					display: 'tiles',
					appCodes: ['PERF_REVIEW', 'TEAM_GOALS', 'INITIATE_PIP'],
				},
				{
					sectionId: 'manager-learning-recognition',
					title: 'Development and Recognition',
					display: 'tiles',
					appCodes: ['TEAM_LEARNING', 'TEAM_SKILLS', 'GIVE_RECOGNITION'],
				},
			],
		},
		{
			pageId: 'hr-workforce',
			title: 'Workforce Operations',
			description:
				'Employee records, profile configuration, data intake, changes, probation, and HR service.',
			sections: [
				{
					sectionId: 'hr-workforce-records',
					title: 'Records and Changes',
					display: 'tiles',
					appCodes: [
						'EMPLOYEE_RECORDS',
						'EMPLOYEE_IMPORT',
						'EMPLOYMENT_CHANGES',
						'PROBATION_MANAGEMENT',
					],
				},
				{
					sectionId: 'hr-workforce-service',
					title: 'Configuration and Service',
					display: 'tiles',
					appCodes: [
						'ORGANIZATION_STRUCTURE',
						'IDENTIFICATION_TYPES',
						'LOOKUP_VALUES',
						'EMPLOYEE_PROFILE_CONFIGURATION',
						'HR_SERVICE_DESK',
					],
				},
			],
		},
		{
			pageId: 'hr-recruitment-lifecycle',
			title: 'Recruitment and Lifecycle',
			description:
				'Candidate acquisition, offers, checks, onboarding, offboarding, alumni, and settlement.',
			sections: [
				{
					sectionId: 'hr-recruitment',
					title: 'Recruitment',
					display: 'tiles',
					appCodes: [
						'JOB_REQUISITIONS',
						'CANDIDATE_PIPELINE',
						'INTERVIEW_OPERATIONS',
						'OFFER_MANAGEMENT',
						'BACKGROUND_CHECKS',
						'REFERRAL_MANAGEMENT',
					],
				},
				{
					sectionId: 'hr-lifecycle',
					title: 'Employee Lifecycle',
					display: 'tiles',
					appCodes: [
						'ONBOARDING_OPERATIONS',
						'OFFBOARDING_OPERATIONS',
						'ALUMNI_MANAGEMENT',
						'FINAL_SETTLEMENTS',
						'REFERENCE_LETTERS',
					],
				},
			],
		},
		{
			pageId: 'hr-time-projects',
			title: 'Projects, Time, and Leave',
			description:
				'Project administration, utilization, attendance, schedules, timesheets, holidays, and leave.',
			sections: [
				{
					sectionId: 'hr-projects',
					title: 'Projects and Positions',
					display: 'tiles',
					appCodes: [
						'POSITIONS',
						'CLIENT_MANAGEMENT',
						'PROJECT_MANAGEMENT',
						'UTILIZATION_POLICIES',
						'PROJECT_DATA_IMPORT',
					],
				},
				{
					sectionId: 'hr-time',
					title: 'Attendance and Time',
					display: 'tiles',
					appCodes: [
						'ATTENDANCE_MANAGEMENT',
						'WORK_SCHEDULES',
						'HOLIDAY_CALENDARS',
						'TIMESHEET_ADMINISTRATION',
					],
				},
				{
					sectionId: 'hr-leave',
					title: 'Leave',
					display: 'tiles',
					appCodes: [
						'LEAVE_ADMINISTRATION',
						'COMP_OFF_ADMINISTRATION',
						'LEAVE_ENCASHMENT',
						'LEAVE_POLICIES',
					],
				},
			],
		},
		{
			pageId: 'hr-pay-expenses',
			title: 'Payroll, Compensation, and Expenses',
			description:
				'Restricted payroll, compensation, benefits, expense, travel, and reimbursement operations.',
			sections: [
				{
					sectionId: 'hr-payroll',
					title: 'Payroll',
					display: 'tiles',
					appCodes: [
						'PAYROLL_RUNS',
						'PAYROLL_INPUTS',
						'PAYROLL_COMPLIANCE',
						'TAX_DECLARATION_ADMIN',
					],
				},
				{
					sectionId: 'hr-compensation',
					title: 'Compensation and Benefits',
					display: 'tiles',
					appCodes: ['SALARY_REVISIONS', 'BENEFIT_PROGRAMS', 'COMPENSATION_CYCLES'],
				},
				{
					sectionId: 'hr-expenses',
					title: 'Expenses and Reimbursements',
					display: 'tiles',
					appCodes: ['EXPENSE_ADMINISTRATION', 'TRAVEL_ADVANCE_ADMIN', 'REIMBURSEMENT_RUNS'],
				},
			],
		},
		{
			pageId: 'hr-talent',
			title: 'Talent and Development',
			description: 'Skills, competencies, learning, performance cycles, and improvement plans.',
			sections: [
				{
					sectionId: 'hr-skills-learning',
					title: 'Skills and Learning',
					display: 'tiles',
					appCodes: [
						'SKILLS_CATALOGUE',
						'COMPETENCY_CATALOGUE',
						'LEARNING_PROGRAMS',
						'LEARNING_PATHS',
					],
				},
				{
					sectionId: 'hr-performance',
					title: 'Performance',
					display: 'tiles',
					appCodes: ['PERFORMANCE_CYCLES', 'PIP_MANAGEMENT'],
				},
			],
		},
		{
			pageId: 'hr-governance-assets-engagement',
			title: 'Documents, Governance, Assets, and Engagement',
			description:
				'Documents, policy, compliance, workflow, assets, surveys, announcements, and recognition programs.',
			sections: [
				{
					sectionId: 'hr-documents-governance',
					title: 'Documents and Governance',
					display: 'tiles',
					appCodes: [
						'EMPLOYEE_DOCUMENTS',
						'DOCUMENT_REQUESTS',
						'POLICY_MANAGEMENT',
						'COMPLIANCE_TRACKING',
						'WORKFLOW_OPERATIONS',
						'DOCUMENT_TYPES',
						'DOCUMENT_TEMPLATES',
					],
				},
				{
					sectionId: 'hr-assets',
					title: 'Assets',
					display: 'tiles',
					appCodes: ['ASSET_ADMINISTRATION', 'ASSET_MAINTENANCE'],
				},
				{
					sectionId: 'hr-engagement',
					title: 'Engagement',
					display: 'tiles',
					appCodes: ['ENGAGEMENT_SURVEYS', 'ANNOUNCEMENT_MANAGEMENT', 'RECOGNITION_PROGRAMS'],
				},
			],
		},
		{
			pageId: 'analytics-workforce-operations',
			title: 'Workforce and Operations Analytics',
			description:
				'Workforce, attendance, leave, time, projects, expenses, assets, and compliance.',
			sections: [
				{
					sectionId: 'analytics-workforce',
					title: 'Workforce',
					display: 'tiles',
					appCodes: [
						'HR_ANALYTICS',
						'HEADCOUNT_ANALYSIS',
						'ATTRITION_DASHBOARD',
						'ONBOARDING_METRICS',
					],
				},
				{
					sectionId: 'analytics-time-operations',
					title: 'Time and Operations',
					display: 'tiles',
					appCodes: [
						'ATTENDANCE_REPORT',
						'LEAVE_TRENDS',
						'TIMESHEET_COMPLIANCE',
						'PROJECT_UTILIZATION',
						'EXPENSE_ANALYSIS',
						'ASSET_UTILIZATION',
						'COMPLIANCE_DASHBOARD',
					],
				},
			],
		},
		{
			pageId: 'analytics-finance-talent',
			title: 'Finance and Talent Analytics',
			description:
				'Restricted pay insights, hiring, skills, performance, learning, and governed report authoring.',
			sections: [
				{
					sectionId: 'analytics-finance',
					title: 'Pay and Benefits',
					display: 'tiles',
					appCodes: ['PAYROLL_SUMMARY', 'BENEFITS_COST_ANALYSIS', 'COMPENSATION_ANALYSIS'],
				},
				{
					sectionId: 'analytics-talent',
					title: 'Talent',
					display: 'tiles',
					appCodes: [
						'HIRING_FUNNEL',
						'SKILL_GAP_REPORT',
						'PERFORMANCE_INSIGHTS',
						'TRAINING_EFFECTIVENESS',
					],
				},
				{
					sectionId: 'analytics-authoring',
					title: 'Reporting',
					display: 'links',
					appCodes: ['REPORT_BUILDER'],
				},
			],
		},
		{
			pageId: 'admin-identity-access',
			title: 'Identity and Access',
			description:
				'Domains, sign-in, users, sessions, credentials, roles, assignments, navigation, and reviews.',
			sections: [
				{
					sectionId: 'admin-identity',
					title: 'Identity',
					display: 'tiles',
					appCodes: [
						'DOMAIN_CONFIGURATION',
						'SSO_CONFIGURATION',
						'IDENTITY_ADMINISTRATION',
						'SECURITY_POLICIES',
						'ACTIVE_SESSIONS',
						'API_CREDENTIALS',
					],
				},
				{
					sectionId: 'admin-access',
					title: 'Access',
					display: 'tiles',
					appCodes: [
						'ROLE_MANAGEMENT',
						'ACCESS_ASSIGNMENTS',
						'APP_CATALOGUE_CONFIGURATION',
						'TENANT_ACCESS_REVIEWS',
					],
				},
			],
		},
		{
			pageId: 'admin-communication',
			title: 'Communication and Integrations',
			description: 'Tenant email, notification templates and rules, and outbound webhooks.',
			sections: [
				{
					sectionId: 'admin-notifications',
					title: 'Communication',
					display: 'tiles',
					appCodes: [
						'EMAIL_SENDER_CONFIGURATION',
						'NOTIFICATION_TEMPLATES',
						'NOTIFICATION_RULES',
						'OUTBOUND_WEBHOOKS',
					],
				},
			],
		},
		{
			pageId: 'admin-reference-data',
			title: 'Reference Data and Policies',
			description:
				'People, documents, workflows, time, expense, pay, asset, and lifecycle definitions.',
			sections: [
				{
					sectionId: 'admin-people-documents',
					title: 'People and Documents',
					display: 'tiles',
					appCodes: [
						'ORGANIZATION_STRUCTURE',
						'IDENTIFICATION_TYPES',
						'LOOKUP_VALUES',
						'JOB_CATALOGUE',
						'POSITION_REQUIREMENTS',
						'DOCUMENT_TYPES',
						'DOCUMENT_TEMPLATES',
					],
				},
				{
					sectionId: 'admin-process-time',
					title: 'Process and Time',
					display: 'tiles',
					appCodes: [
						'WORKFLOW_DEFINITIONS',
						'WORK_SCHEDULE_TEMPLATES',
						'TIMESHEET_POLICIES',
						'EXPENSE_POLICIES',
					],
				},
				{
					sectionId: 'admin-pay-assets-lifecycle',
					title: 'Pay, Assets, and Lifecycle',
					display: 'tiles',
					appCodes: [
						'COMPENSATION_COMPONENTS',
						'BENEFIT_CATALOGUE',
						'ASSET_CATEGORIES',
						'TASK_TEMPLATES',
					],
				},
			],
		},
		{
			pageId: 'admin-assurance-governance',
			title: 'Assurance and Governance',
			description:
				'Tenant audit evidence, sensitive access, exports, retention, and data-rights operations.',
			sections: [
				{
					sectionId: 'admin-assurance',
					title: 'Assurance',
					display: 'tiles',
					appCodes: ['AUDIT_LOG', 'SENSITIVE_ACCESS_LOG', 'DATA_EXPORT_LOG'],
				},
				{
					sectionId: 'admin-privacy',
					title: 'Privacy and Governance',
					display: 'tiles',
					appCodes: ['RETENTION_POLICIES', 'DATA_RIGHTS_REQUESTS'],
				},
			],
		},
	],
	businessRoles: [
		{
			roleId: 'employee',
			title: 'Employee',
			description: 'Standard workforce self-service access.',
			catalogueIds: ['employee-self-service'],
			spaceIds: ['employee'],
		},
		{
			roleId: 'manager',
			title: 'Manager',
			description: 'Employee self-service plus team-management responsibilities.',
			catalogueIds: ['employee-self-service', 'manager-self-service'],
			spaceIds: ['employee', 'manager'],
		},
		{
			roleId: 'hr-specialist',
			title: 'HR or Functional Specialist',
			description: 'Employee self-service plus explicitly authorised HR specialist operations.',
			catalogueIds: ['employee-self-service', 'hr-specialist-operations'],
			spaceIds: ['employee', 'hr-operations'],
		},
		{
			roleId: 'people-analyst',
			title: 'People Analyst',
			description: 'Employee self-service plus governed analytics and reporting.',
			catalogueIds: ['employee-self-service', 'people-analytics'],
			spaceIds: ['employee', 'analytics'],
		},
		{
			roleId: 'tenant-administrator',
			title: 'Tenant Administrator',
			description: 'Employee self-service plus explicitly authorised tenant administration.',
			catalogueIds: ['employee-self-service', 'tenant-administration'],
			spaceIds: ['employee', 'tenant-administration'],
		},
	],
	domains: [
		{
			domain: 'access-control',
			deliveryWaves: ['HCM-1'],
			apps: [
				'ACCESS_ASSIGNMENTS',
				'APP_CATALOGUE_CONFIGURATION',
				'ROLE_MANAGEMENT',
				'TENANT_ACCESS_REVIEWS',
			],
		},
		{
			domain: 'analytics',
			deliveryWaves: ['HCM-9'],
			apps: [
				'ASSET_UTILIZATION',
				'ATTENDANCE_REPORT',
				'ATTRITION_DASHBOARD',
				'BENEFITS_COST_ANALYSIS',
				'COMPENSATION_ANALYSIS',
				'COMPLIANCE_DASHBOARD',
				'EXPENSE_ANALYSIS',
				'HEADCOUNT_ANALYSIS',
				'HIRING_FUNNEL',
				'HR_ANALYTICS',
				'LEAVE_TRENDS',
				'ONBOARDING_METRICS',
				'PAYROLL_SUMMARY',
				'PERFORMANCE_INSIGHTS',
				'PROJECT_UTILIZATION',
				'REPORT_BUILDER',
				'SKILL_GAP_REPORT',
				'TIMESHEET_COMPLIANCE',
				'TRAINING_EFFECTIVENESS',
			],
		},
		{
			domain: 'assets',
			deliveryWaves: ['HCM-8'],
			apps: ['ASSET_ADMINISTRATION', 'ASSET_CATEGORIES', 'ASSET_MAINTENANCE', 'MY_ASSETS'],
		},
		{
			domain: 'attendance',
			deliveryWaves: ['HCM-3'],
			apps: [
				'APPROVE_ATTENDANCE',
				'ATTENDANCE_CORRECTIONS',
				'ATTENDANCE_MANAGEMENT',
				'HOLIDAY_CALENDARS',
				'MY_ATTENDANCE',
				'MY_SCHEDULE',
				'SHIFT_PLANNING',
				'TEAM_ATTENDANCE',
				'WORK_SCHEDULES',
				'WORK_SCHEDULE_TEMPLATES',
			],
		},
		{
			domain: 'audit',
			deliveryWaves: ['HCM-1'],
			apps: ['AUDIT_LOG', 'DATA_EXPORT_LOG', 'MY_ACTIVITY', 'SENSITIVE_ACCESS_LOG'],
		},
		{
			domain: 'compensation-benefits',
			deliveryWaves: ['HCM-6'],
			apps: [
				'BENEFIT_CATALOGUE',
				'BENEFIT_PROGRAMS',
				'COMPENSATION_COMPONENTS',
				'COMPENSATION_CYCLES',
				'MY_BENEFITS',
				'MY_COMPENSATION',
				'SALARY_REVISIONS',
			],
		},
		{
			domain: 'documents',
			deliveryWaves: ['HCM-1'],
			apps: [
				'DOCUMENT_REQUESTS',
				'DOCUMENT_TEMPLATES',
				'DOCUMENT_TYPES',
				'EMPLOYEE_DOCUMENTS',
				'MY_DOCUMENTS',
			],
		},
		{
			domain: 'employee',
			deliveryWaves: ['HCM-2'],
			apps: [
				'EMPLOYEE_DIRECTORY',
				'EMPLOYEE_IMPORT',
				'EMPLOYEE_PROFILE_CONFIGURATION',
				'EMPLOYEE_RECORDS',
				'EMPLOYMENT_CHANGES',
				'HR_SERVICE_DESK',
				'MY_HR_REQUESTS',
				'MY_PROFILE',
				'PROBATION_MANAGEMENT',
				'PROBATION_REVIEW',
				'TEAM_DIRECTORY',
			],
		},
		{
			domain: 'engagement',
			deliveryWaves: ['HCM-8'],
			apps: [
				'ANNOUNCEMENTS',
				'ANNOUNCEMENT_MANAGEMENT',
				'ENGAGEMENT_SURVEYS',
				'GIVE_RECOGNITION',
				'RECOGNITION',
				'RECOGNITION_PROGRAMS',
				'SURVEYS',
			],
		},
		{
			domain: 'expenses',
			deliveryWaves: ['HCM-6'],
			apps: [
				'APPROVE_EXPENSES',
				'EXPENSE_ADMINISTRATION',
				'EXPENSE_POLICIES',
				'MY_EXPENSES',
				'MY_TRAVEL_ADVANCES',
				'REIMBURSEMENT_RUNS',
				'TEAM_EXPENSES',
				'TRAVEL_ADVANCE_ADMIN',
			],
		},
		{
			domain: 'governance',
			deliveryWaves: ['HCM-8'],
			apps: [
				'COMPLIANCE_TRACKING',
				'DATA_RIGHTS_REQUESTS',
				'POLICY_ACKNOWLEDGEMENTS',
				'POLICY_MANAGEMENT',
				'RETENTION_POLICIES',
			],
		},
		{
			domain: 'identity-access',
			deliveryWaves: ['HCM-1'],
			apps: [
				'ACTIVE_SESSIONS',
				'API_CREDENTIALS',
				'DOMAIN_CONFIGURATION',
				'IDENTITY_ADMINISTRATION',
				'MY_SECURITY',
				'SECURITY_POLICIES',
				'SSO_CONFIGURATION',
			],
		},
		{
			domain: 'job-architecture',
			deliveryWaves: ['HCM-2'],
			apps: ['JOB_CATALOGUE', 'POSITIONS', 'POSITION_REQUIREMENTS'],
		},
		{
			domain: 'learning',
			deliveryWaves: ['HCM-7'],
			apps: ['LEARNING_PATHS', 'LEARNING_PROGRAMS', 'MY_LEARNING', 'TEAM_LEARNING'],
		},
		{
			domain: 'leave',
			deliveryWaves: ['HCM-3'],
			apps: [
				'APPLY_LEAVE',
				'APPROVE_LEAVES',
				'COMP_OFF_ADMINISTRATION',
				'COMP_OFF_ENCASHMENT',
				'LEAVE_ADMINISTRATION',
				'LEAVE_BALANCE',
				'LEAVE_ENCASHMENT',
				'LEAVE_POLICIES',
				'TEAM_CALENDAR',
			],
		},
		{
			domain: 'notifications',
			deliveryWaves: ['HCM-1'],
			apps: [
				'EMAIL_SENDER_CONFIGURATION',
				'MY_NOTIFICATIONS',
				'MY_NOTIFICATION_PREFERENCES',
				'NOTIFICATION_RULES',
				'NOTIFICATION_TEMPLATES',
				'OUTBOUND_WEBHOOKS',
			],
		},
		{
			domain: 'offboarding',
			deliveryWaves: ['HCM-5'],
			apps: [
				'ALUMNI_MANAGEMENT',
				'FINAL_SETTLEMENTS',
				'MY_EXIT',
				'OFFBOARDING_OPERATIONS',
				'REFERENCE_LETTERS',
				'TEAM_OFFBOARDING',
			],
		},
		{
			domain: 'onboarding',
			deliveryWaves: ['HCM-5'],
			apps: ['MY_ONBOARDING', 'ONBOARDING_OPERATIONS', 'TASK_TEMPLATES', 'TEAM_ONBOARDING'],
		},
		{
			domain: 'payroll',
			deliveryWaves: ['HCM-6'],
			apps: [
				'MY_PAYSLIPS',
				'MY_TAX_DECLARATIONS',
				'MY_TAX_DOCUMENTS',
				'PAYROLL_COMPLIANCE',
				'PAYROLL_INPUTS',
				'PAYROLL_RUNS',
				'TAX_DECLARATION_ADMIN',
			],
		},
		{
			domain: 'performance',
			deliveryWaves: ['HCM-7'],
			apps: [
				'GIVE_FEEDBACK',
				'INITIATE_PIP',
				'MY_GOALS',
				'MY_PERFORMANCE',
				'MY_PIP',
				'PERFORMANCE_CYCLES',
				'PERF_REVIEW',
				'PIP_MANAGEMENT',
				'TEAM_GOALS',
			],
		},
		{
			domain: 'projects',
			deliveryWaves: ['HCM-4'],
			apps: [
				'ASSIGN_PROJECTS',
				'CLIENT_MANAGEMENT',
				'MY_PROJECTS',
				'PROJECT_DATA_IMPORT',
				'PROJECT_MANAGEMENT',
				'TEAM_UTILIZATION',
				'UTILIZATION_POLICIES',
			],
		},
		{
			domain: 'recruitment',
			deliveryWaves: ['HCM-5'],
			apps: [
				'BACKGROUND_CHECKS',
				'CANDIDATE_PIPELINE',
				'EMPLOYEE_REFERRALS',
				'INTERVIEW_OPERATIONS',
				'INTERVIEW_PANEL',
				'JOB_REQUISITIONS',
				'OFFER_MANAGEMENT',
				'REFERRAL_MANAGEMENT',
			],
		},
		{
			domain: 'skills',
			deliveryWaves: ['HCM-7'],
			apps: ['COMPETENCY_CATALOGUE', 'MY_SKILLS', 'SKILLS_CATALOGUE', 'TEAM_SKILLS'],
		},
		{
			domain: 'timesheet',
			deliveryWaves: ['HCM-4'],
			apps: [
				'APPROVE_TIMESHEETS',
				'MY_TIMESHEET',
				'TEAM_TIMESHEET',
				'TIMESHEET_ADMINISTRATION',
				'TIMESHEET_POLICIES',
			],
		},
		{
			domain: 'workflow',
			deliveryWaves: ['HCM-3'],
			apps: ['MY_APPROVALS', 'MY_TASKS', 'WORKFLOW_DEFINITIONS', 'WORKFLOW_OPERATIONS'],
		},
		{
			domain: 'workforce-foundation',
			deliveryWaves: ['HCM-2'],
			apps: ['IDENTIFICATION_TYPES', 'LOOKUP_VALUES', 'ORG_CHART', 'ORGANIZATION_STRUCTURE'],
		},
	],
}
