-- Ownership: workforce-foundation. Global product reference data and the extensions HCM-2 needs
-- for effective-date exclusion constraints and trigram name search. No tenant data.
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA hcm;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA hcm;

CREATE TABLE hcm.country (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z]{2}$'),
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
  is_supported boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL,
  active boolean NOT NULL DEFAULT true
);
CREATE TABLE hcm.currency (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z]{3}$'),
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 100),
  symbol text NOT NULL CHECK (length(symbol) BETWEEN 1 AND 10),
  minor_unit_digits smallint NOT NULL CHECK (minor_unit_digits BETWEEN 0 AND 4),
  active boolean NOT NULL DEFAULT true
);
CREATE TABLE hcm.gender (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z][A-Z0-9_]{1,39}$'),
  name text NOT NULL,
  statutory_class text NOT NULL CHECK (statutory_class IN ('Female','Male','Other','NotDisclosed')),
  sort_order integer NOT NULL,
  active boolean NOT NULL DEFAULT true
);
CREATE TABLE hcm.marital_status (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z][A-Z0-9_]{1,39}$'),
  name text NOT NULL,
  sort_order integer NOT NULL,
  active boolean NOT NULL DEFAULT true
);
CREATE TABLE hcm.relationship_type (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z][A-Z0-9_]{1,39}$'),
  name text NOT NULL,
  inverse_code text,
  is_family_relation boolean NOT NULL,
  is_eligible_as_dependent boolean NOT NULL,
  is_eligible_as_nominee boolean NOT NULL,
  sort_order integer NOT NULL,
  active boolean NOT NULL DEFAULT true
);
CREATE TABLE hcm.identification_type (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z][A-Z0-9_]{1,39}$'),
  name text NOT NULL,
  country_code text REFERENCES hcm.country(code),
  validation_pattern text,
  validation_description text NOT NULL,
  is_unique_per_person boolean NOT NULL,
  requires_masking boolean NOT NULL,
  is_required_for_payroll boolean NOT NULL,
  sort_order integer NOT NULL,
  active boolean NOT NULL DEFAULT true
);
INSERT INTO hcm.country(code,name,is_supported,sort_order) VALUES
  ('AF','Afghanistan',false,1),
  ('AX','Åland Islands',false,2),
  ('AL','Albania',false,3),
  ('DZ','Algeria',false,4),
  ('AS','American Samoa',false,5),
  ('AD','Andorra',false,6),
  ('AO','Angola',false,7),
  ('AI','Anguilla',false,8),
  ('AQ','Antarctica',false,9),
  ('AG','Antigua & Barbuda',false,10),
  ('AR','Argentina',false,11),
  ('AM','Armenia',false,12),
  ('AW','Aruba',false,13),
  ('AU','Australia',false,14),
  ('AT','Austria',false,15),
  ('AZ','Azerbaijan',false,16),
  ('BS','Bahamas',false,17),
  ('BH','Bahrain',false,18),
  ('BD','Bangladesh',false,19),
  ('BB','Barbados',false,20),
  ('BY','Belarus',false,21),
  ('BE','Belgium',false,22),
  ('BZ','Belize',false,23),
  ('BJ','Benin',false,24),
  ('BM','Bermuda',false,25),
  ('BT','Bhutan',false,26),
  ('BO','Bolivia',false,27),
  ('BA','Bosnia & Herzegovina',false,28),
  ('BW','Botswana',false,29),
  ('BV','Bouvet Island',false,30),
  ('BR','Brazil',false,31),
  ('IO','British Indian Ocean Territory',false,32),
  ('VG','British Virgin Islands',false,33),
  ('BN','Brunei',false,34),
  ('BG','Bulgaria',false,35),
  ('BF','Burkina Faso',false,36),
  ('BI','Burundi',false,37),
  ('KH','Cambodia',false,38),
  ('CM','Cameroon',false,39),
  ('CA','Canada',false,40),
  ('CV','Cape Verde',false,41),
  ('BQ','Caribbean Netherlands',false,42),
  ('KY','Cayman Islands',false,43),
  ('CF','Central African Republic',false,44),
  ('TD','Chad',false,45),
  ('CL','Chile',false,46),
  ('CN','China',false,47),
  ('CX','Christmas Island',false,48),
  ('CC','Cocos (Keeling) Islands',false,49),
  ('CO','Colombia',false,50),
  ('KM','Comoros',false,51),
  ('CG','Congo - Brazzaville',false,52),
  ('CD','Congo - Kinshasa',false,53),
  ('CK','Cook Islands',false,54),
  ('CR','Costa Rica',false,55),
  ('CI','Côte d’Ivoire',false,56),
  ('HR','Croatia',false,57),
  ('CU','Cuba',false,58),
  ('CW','Curaçao',false,59),
  ('CY','Cyprus',false,60),
  ('CZ','Czechia',false,61),
  ('DK','Denmark',false,62),
  ('DJ','Djibouti',false,63),
  ('DM','Dominica',false,64),
  ('DO','Dominican Republic',false,65),
  ('EC','Ecuador',false,66),
  ('EG','Egypt',false,67),
  ('SV','El Salvador',false,68),
  ('GQ','Equatorial Guinea',false,69),
  ('ER','Eritrea',false,70),
  ('EE','Estonia',false,71),
  ('SZ','Eswatini',false,72),
  ('ET','Ethiopia',false,73),
  ('FK','Falkland Islands',false,74),
  ('FO','Faroe Islands',false,75),
  ('FJ','Fiji',false,76),
  ('FI','Finland',false,77),
  ('FR','France',false,78),
  ('GF','French Guiana',false,79),
  ('PF','French Polynesia',false,80),
  ('TF','French Southern Territories',false,81),
  ('GA','Gabon',false,82),
  ('GM','Gambia',false,83),
  ('GE','Georgia',false,84),
  ('DE','Germany',false,85),
  ('GH','Ghana',false,86),
  ('GI','Gibraltar',false,87),
  ('GR','Greece',false,88),
  ('GL','Greenland',false,89),
  ('GD','Grenada',false,90),
  ('GP','Guadeloupe',false,91),
  ('GU','Guam',false,92),
  ('GT','Guatemala',false,93),
  ('GG','Guernsey',false,94),
  ('GN','Guinea',false,95),
  ('GW','Guinea-Bissau',false,96),
  ('GY','Guyana',false,97),
  ('HT','Haiti',false,98),
  ('HM','Heard & McDonald Islands',false,99),
  ('HN','Honduras',false,100),
  ('HK','Hong Kong SAR China',false,101),
  ('HU','Hungary',false,102),
  ('IS','Iceland',false,103),
  ('IN','India',true,104),
  ('ID','Indonesia',false,105),
  ('IR','Iran',false,106),
  ('IQ','Iraq',false,107),
  ('IE','Ireland',false,108),
  ('IM','Isle of Man',false,109),
  ('IL','Israel',false,110),
  ('IT','Italy',false,111),
  ('JM','Jamaica',false,112),
  ('JP','Japan',false,113),
  ('JE','Jersey',false,114),
  ('JO','Jordan',false,115),
  ('KZ','Kazakhstan',false,116),
  ('KE','Kenya',false,117),
  ('KI','Kiribati',false,118),
  ('KW','Kuwait',false,119),
  ('KG','Kyrgyzstan',false,120),
  ('LA','Laos',false,121),
  ('LV','Latvia',false,122),
  ('LB','Lebanon',false,123),
  ('LS','Lesotho',false,124),
  ('LR','Liberia',false,125),
  ('LY','Libya',false,126),
  ('LI','Liechtenstein',false,127),
  ('LT','Lithuania',false,128),
  ('LU','Luxembourg',false,129),
  ('MO','Macao SAR China',false,130),
  ('MG','Madagascar',false,131),
  ('MW','Malawi',false,132),
  ('MY','Malaysia',false,133),
  ('MV','Maldives',false,134),
  ('ML','Mali',false,135),
  ('MT','Malta',false,136),
  ('MH','Marshall Islands',false,137),
  ('MQ','Martinique',false,138),
  ('MR','Mauritania',false,139),
  ('MU','Mauritius',false,140),
  ('YT','Mayotte',false,141),
  ('MX','Mexico',false,142),
  ('FM','Micronesia',false,143),
  ('MD','Moldova',false,144),
  ('MC','Monaco',false,145),
  ('MN','Mongolia',false,146),
  ('ME','Montenegro',false,147),
  ('MS','Montserrat',false,148),
  ('MA','Morocco',false,149),
  ('MZ','Mozambique',false,150),
  ('MM','Myanmar (Burma)',false,151),
  ('NA','Namibia',false,152),
  ('NR','Nauru',false,153),
  ('NP','Nepal',false,154),
  ('NL','Netherlands',false,155),
  ('NC','New Caledonia',false,156),
  ('NZ','New Zealand',false,157),
  ('NI','Nicaragua',false,158),
  ('NE','Niger',false,159),
  ('NG','Nigeria',false,160),
  ('NU','Niue',false,161),
  ('NF','Norfolk Island',false,162),
  ('KP','North Korea',false,163),
  ('MK','North Macedonia',false,164),
  ('MP','Northern Mariana Islands',false,165),
  ('NO','Norway',false,166),
  ('OM','Oman',false,167),
  ('PK','Pakistan',false,168),
  ('PW','Palau',false,169),
  ('PS','Palestinian Territories',false,170),
  ('PA','Panama',false,171),
  ('PG','Papua New Guinea',false,172),
  ('PY','Paraguay',false,173),
  ('PE','Peru',false,174),
  ('PH','Philippines',false,175),
  ('PN','Pitcairn Islands',false,176),
  ('PL','Poland',false,177),
  ('PT','Portugal',false,178),
  ('PR','Puerto Rico',false,179),
  ('QA','Qatar',false,180),
  ('RE','Réunion',false,181),
  ('RO','Romania',false,182),
  ('RU','Russia',false,183),
  ('RW','Rwanda',false,184),
  ('WS','Samoa',false,185),
  ('SM','San Marino',false,186),
  ('ST','São Tomé & Príncipe',false,187),
  ('SA','Saudi Arabia',false,188),
  ('SN','Senegal',false,189),
  ('RS','Serbia',false,190),
  ('SC','Seychelles',false,191),
  ('SL','Sierra Leone',false,192),
  ('SG','Singapore',false,193),
  ('SX','Sint Maarten',false,194),
  ('SK','Slovakia',false,195),
  ('SI','Slovenia',false,196),
  ('SB','Solomon Islands',false,197),
  ('SO','Somalia',false,198),
  ('ZA','South Africa',false,199),
  ('GS','South Georgia & South Sandwich Islands',false,200),
  ('KR','South Korea',false,201),
  ('SS','South Sudan',false,202),
  ('ES','Spain',false,203),
  ('LK','Sri Lanka',false,204),
  ('BL','St. Barthélemy',false,205),
  ('SH','St. Helena',false,206),
  ('KN','St. Kitts & Nevis',false,207),
  ('LC','St. Lucia',false,208),
  ('MF','St. Martin',false,209),
  ('PM','St. Pierre & Miquelon',false,210),
  ('VC','St. Vincent & Grenadines',false,211),
  ('SD','Sudan',false,212),
  ('SR','Suriname',false,213),
  ('SJ','Svalbard & Jan Mayen',false,214),
  ('SE','Sweden',false,215),
  ('CH','Switzerland',false,216),
  ('SY','Syria',false,217),
  ('TW','Taiwan',false,218),
  ('TJ','Tajikistan',false,219),
  ('TZ','Tanzania',false,220),
  ('TH','Thailand',false,221),
  ('TL','Timor-Leste',false,222),
  ('TG','Togo',false,223),
  ('TK','Tokelau',false,224),
  ('TO','Tonga',false,225),
  ('TT','Trinidad & Tobago',false,226),
  ('TN','Tunisia',false,227),
  ('TR','Türkiye',false,228),
  ('TM','Turkmenistan',false,229),
  ('TC','Turks & Caicos Islands',false,230),
  ('TV','Tuvalu',false,231),
  ('UM','U.S. Outlying Islands',false,232),
  ('VI','U.S. Virgin Islands',false,233),
  ('UG','Uganda',false,234),
  ('UA','Ukraine',false,235),
  ('AE','United Arab Emirates',false,236),
  ('GB','United Kingdom',true,237),
  ('US','United States',true,238),
  ('UY','Uruguay',false,239),
  ('UZ','Uzbekistan',false,240),
  ('VU','Vanuatu',false,241),
  ('VA','Vatican City',false,242),
  ('VE','Venezuela',false,243),
  ('VN','Vietnam',false,244),
  ('WF','Wallis & Futuna',false,245),
  ('EH','Western Sahara',false,246),
  ('YE','Yemen',false,247),
  ('ZM','Zambia',false,248),
  ('ZW','Zimbabwe',false,249);
INSERT INTO hcm.currency(code,name,symbol,minor_unit_digits) VALUES
  ('AED','United Arab Emirates Dirham','AED',2),
  ('AFN','Afghan Afghani','AFN',0),
  ('ALL','Albanian Lek','ALL',0),
  ('AMD','Armenian Dram','AMD',2),
  ('ANG','Netherlands Antillean Guilder','ANG',2),
  ('AOA','Angolan Kwanza','AOA',2),
  ('ARS','Argentine Peso','ARS',2),
  ('AUD','Australian Dollar','A$',2),
  ('AWG','Aruban Florin','AWG',2),
  ('AZN','Azerbaijani Manat','AZN',2),
  ('BAM','Bosnia-Herzegovina Convertible Mark','BAM',2),
  ('BBD','Barbadian Dollar','BBD',2),
  ('BDT','Bangladeshi Taka','BDT',2),
  ('BGN','Bulgarian Lev','BGN',2),
  ('BHD','Bahraini Dinar','BHD',3),
  ('BIF','Burundian Franc','BIF',0),
  ('BMD','Bermudan Dollar','BMD',2),
  ('BND','Brunei Dollar','BND',2),
  ('BOB','Bolivian Boliviano','BOB',2),
  ('BRL','Brazilian Real','R$',2),
  ('BSD','Bahamian Dollar','BSD',2),
  ('BTN','Bhutanese Ngultrum','BTN',2),
  ('BWP','Botswanan Pula','BWP',2),
  ('BYN','Belarusian Ruble','BYN',2),
  ('BZD','Belize Dollar','BZD',2),
  ('CAD','Canadian Dollar','CA$',2),
  ('CDF','Congolese Franc','CDF',2),
  ('CHF','Swiss Franc','CHF',2),
  ('CLP','Chilean Peso','CLP',0),
  ('CNY','Chinese Yuan','CN¥',2),
  ('COP','Colombian Peso','COP',0),
  ('CRC','Costa Rican Colón','CRC',2),
  ('CUC','Cuban Convertible Peso','CUC',2),
  ('CUP','Cuban Peso','CUP',2),
  ('CVE','Cape Verdean Escudo','CVE',2),
  ('CZK','Czech Koruna','CZK',2),
  ('DJF','Djiboutian Franc','DJF',0),
  ('DKK','Danish Krone','DKK',2),
  ('DOP','Dominican Peso','DOP',2),
  ('DZD','Algerian Dinar','DZD',2),
  ('EGP','Egyptian Pound','EGP',2),
  ('ERN','Eritrean Nakfa','ERN',2),
  ('ETB','Ethiopian Birr','ETB',2),
  ('EUR','Euro','€',2),
  ('FJD','Fijian Dollar','FJD',2),
  ('FKP','Falkland Islands Pound','FKP',2),
  ('GBP','British Pound','£',2),
  ('GEL','Georgian Lari','GEL',2),
  ('GHS','Ghanaian Cedi','GHS',2),
  ('GIP','Gibraltar Pound','GIP',2),
  ('GMD','Gambian Dalasi','GMD',2),
  ('GNF','Guinean Franc','GNF',0),
  ('GTQ','Guatemalan Quetzal','GTQ',2),
  ('GYD','Guyanaese Dollar','GYD',2),
  ('HKD','Hong Kong Dollar','HK$',2),
  ('HNL','Honduran Lempira','HNL',2),
  ('HRK','Croatian Kuna','HRK',2),
  ('HTG','Haitian Gourde','HTG',2),
  ('HUF','Hungarian Forint','HUF',0),
  ('IDR','Indonesian Rupiah','IDR',0),
  ('ILS','Israeli New Shekel','₪',2),
  ('INR','Indian Rupee','₹',2),
  ('IQD','Iraqi Dinar','IQD',0),
  ('IRR','Iranian Rial','IRR',0),
  ('ISK','Icelandic Króna','ISK',0),
  ('JMD','Jamaican Dollar','JMD',2),
  ('JOD','Jordanian Dinar','JOD',3),
  ('JPY','Japanese Yen','¥',0),
  ('KES','Kenyan Shilling','KES',2),
  ('KGS','Kyrgyz Som','KGS',2),
  ('KHR','Cambodian Riel','KHR',2),
  ('KMF','Comorian Franc','KMF',0),
  ('KPW','North Korean Won','KPW',0),
  ('KRW','South Korean Won','₩',0),
  ('KWD','Kuwaiti Dinar','KWD',3),
  ('KYD','Cayman Islands Dollar','KYD',2),
  ('KZT','Kazakhstani Tenge','KZT',2),
  ('LAK','Laotian Kip','LAK',0),
  ('LBP','Lebanese Pound','LBP',0),
  ('LKR','Sri Lankan Rupee','LKR',2),
  ('LRD','Liberian Dollar','LRD',2),
  ('LSL','Lesotho Loti','LSL',2),
  ('LYD','Libyan Dinar','LYD',3),
  ('MAD','Moroccan Dirham','MAD',2),
  ('MDL','Moldovan Leu','MDL',2),
  ('MGA','Malagasy Ariary','MGA',0),
  ('MKD','Macedonian Denar','MKD',2),
  ('MMK','Myanmar Kyat','MMK',0),
  ('MNT','Mongolian Tugrik','MNT',2),
  ('MOP','Macanese Pataca','MOP',2),
  ('MRU','Mauritanian Ouguiya','MRU',2),
  ('MUR','Mauritian Rupee','MUR',2),
  ('MVR','Maldivian Rufiyaa','MVR',2),
  ('MWK','Malawian Kwacha','MWK',2),
  ('MXN','Mexican Peso','MX$',2),
  ('MYR','Malaysian Ringgit','MYR',2),
  ('MZN','Mozambican Metical','MZN',2),
  ('NAD','Namibian Dollar','NAD',2),
  ('NGN','Nigerian Naira','NGN',2),
  ('NIO','Nicaraguan Córdoba','NIO',2),
  ('NOK','Norwegian Krone','NOK',2),
  ('NPR','Nepalese Rupee','NPR',2),
  ('NZD','New Zealand Dollar','NZ$',2),
  ('OMR','Omani Rial','OMR',3),
  ('PAB','Panamanian Balboa','PAB',2),
  ('PEN','Peruvian Sol','PEN',2),
  ('PGK','Papua New Guinean Kina','PGK',2),
  ('PHP','Philippine Peso','₱',2),
  ('PKR','Pakistani Rupee','PKR',0),
  ('PLN','Polish Zloty','PLN',2),
  ('PYG','Paraguayan Guarani','PYG',0),
  ('QAR','Qatari Riyal','QAR',2),
  ('RON','Romanian Leu','RON',2),
  ('RSD','Serbian Dinar','RSD',2),
  ('RUB','Russian Ruble','RUB',2),
  ('RWF','Rwandan Franc','RWF',0),
  ('SAR','Saudi Riyal','SAR',2),
  ('SBD','Solomon Islands Dollar','SBD',2),
  ('SCR','Seychellois Rupee','SCR',2),
  ('SDG','Sudanese Pound','SDG',2),
  ('SEK','Swedish Krona','SEK',2),
  ('SGD','Singapore Dollar','SGD',2),
  ('SHP','St. Helena Pound','SHP',2),
  ('SLE','Sierra Leonean Leone','SLE',2),
  ('SLL','Sierra Leonean Leone (1964—2022)','SLL',0),
  ('SOS','Somali Shilling','SOS',0),
  ('SRD','Surinamese Dollar','SRD',2),
  ('SSP','South Sudanese Pound','SSP',2),
  ('STN','São Tomé & Príncipe Dobra','STN',2),
  ('SVC','Salvadoran Colón','SVC',2),
  ('SYP','Syrian Pound','SYP',0),
  ('SZL','Swazi Lilangeni','SZL',2),
  ('THB','Thai Baht','THB',2),
  ('TJS','Tajikistani Somoni','TJS',2),
  ('TMT','Turkmenistani Manat','TMT',2),
  ('TND','Tunisian Dinar','TND',3),
  ('TOP','Tongan Paʻanga','TOP',2),
  ('TRY','Turkish Lira','TRY',2),
  ('TTD','Trinidad & Tobago Dollar','TTD',2),
  ('TWD','New Taiwan Dollar','NT$',2),
  ('TZS','Tanzanian Shilling','TZS',2),
  ('UAH','Ukrainian Hryvnia','UAH',2),
  ('UGX','Ugandan Shilling','UGX',0),
  ('USD','US Dollar','$',2),
  ('UYU','Uruguayan Peso','UYU',2),
  ('UZS','Uzbekistani Som','UZS',2),
  ('VES','Venezuelan Bolívar','VES',2),
  ('VND','Vietnamese Dong','₫',0),
  ('VUV','Vanuatu Vatu','VUV',0),
  ('WST','Samoan Tala','WST',2),
  ('XAF','Central African CFA Franc','FCFA',0),
  ('XCD','East Caribbean Dollar','EC$',2),
  ('XCG','Caribbean guilder','Cg.',2),
  ('XDR','Special Drawing Rights','XDR',2),
  ('XOF','West African CFA Franc','F CFA',0),
  ('XPF','CFP Franc','CFPF',0),
  ('XSU','Sucre','XSU',2),
  ('YER','Yemeni Rial','YER',0),
  ('ZAR','South African Rand','ZAR',2),
  ('ZMW','Zambian Kwacha','ZMW',2),
  ('ZWG','Zimbabwean Gold','ZWG',2),
  ('ZWL','Zimbabwean Dollar (2009–2024)','ZWL',2);
INSERT INTO hcm.gender(code,name,statutory_class,sort_order) VALUES
  ('FEMALE','Female','Female',1),
  ('MALE','Male','Male',2),
  ('TRANSGENDER','Transgender','Other',3),
  ('NOT_DISCLOSED','Prefer not to say','NotDisclosed',4);
INSERT INTO hcm.marital_status(code,name,sort_order) VALUES
  ('SINGLE','Single',1),
  ('MARRIED','Married',2),
  ('DIVORCED','Divorced',3),
  ('WIDOWED','Widowed',4);
INSERT INTO hcm.relationship_type(code,name,inverse_code,is_family_relation,is_eligible_as_dependent,is_eligible_as_nominee,sort_order) VALUES
  ('SPOUSE','Spouse','SPOUSE',true,true,true,1),
  ('FATHER','Father',NULL,true,true,true,2),
  ('MOTHER','Mother',NULL,true,true,true,3),
  ('SON','Son',NULL,true,true,true,4),
  ('DAUGHTER','Daughter',NULL,true,true,true,5),
  ('BROTHER','Brother',NULL,true,false,true,6),
  ('SISTER','Sister',NULL,true,false,true,7),
  ('GUARDIAN','Guardian',NULL,false,false,false,8),
  ('FRIEND','Friend','FRIEND',false,false,false,9),
  ('OTHER','Other',NULL,false,false,false,10);
INSERT INTO hcm.identification_type(code,name,country_code,validation_pattern,validation_description,is_unique_per_person,requires_masking,is_required_for_payroll,sort_order) VALUES
  ('PAN','Permanent Account Number','IN','^[A-Z]{5}[0-9]{4}[A-Z]$','Five letters, four digits and one letter',true,false,true,1),
  ('AADHAAR','Aadhaar Number','IN','^[0-9]{12}$','Twelve digits',true,true,false,2),
  ('UAN','Universal Account Number','IN','^[0-9]{12}$','Twelve digits',true,false,false,3),
  ('SSN','Social Security Number','US','^[0-9]{3}-?[0-9]{2}-?[0-9]{4}$','Nine digits, optionally grouped 3-2-4',true,true,true,4),
  ('NI_NUMBER','National Insurance Number','GB','^[A-Z]{2}[0-9]{6}[A-D]$','Two letters, six digits and a final letter A to D',true,false,true,5),
  ('PASSPORT','Passport',NULL,'^[A-Z0-9]{6,9}$','Six to nine letters or digits',false,false,false,6),
  ('DRIVING_LICENCE','Driving Licence',NULL,NULL,'Format depends on the issuing authority',false,false,false,7);

-- Existing locations gain a product-owned country reference; all seeded codes are ISO 3166-1.
ALTER TABLE hcm.location ADD CONSTRAINT location_country FOREIGN KEY (country_code) REFERENCES hcm.country(code);

GRANT SELECT ON hcm.country, hcm.currency, hcm.gender, hcm.marital_status, hcm.relationship_type, hcm.identification_type TO hcm_runtime;
