-- Ownership: access-control. HCM-2 business permissions and persona grants from the approved permission register.
PERFORM set_config('hcm.tenant_id','local-dunder-mifflin',true);
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.workforce-foundation.identification-types.read','IDENTIFICATION_TYPES: identification-types.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.workforce-foundation.identification-types.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.workforce-foundation.identification-types.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.workforce-foundation.lookups.read','LOOKUP_VALUES: lookups.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.workforce-foundation.lookups.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.workforce-foundation.lookups.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.workforce-foundation.lookups.manage','LOOKUP_VALUES: lookups.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.workforce-foundation.lookups.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.workforce-foundation.structure.read','ORGANIZATION_STRUCTURE: structure.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.workforce-foundation.structure.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.workforce-foundation.structure.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.workforce-foundation.structure.manage','ORGANIZATION_STRUCTURE: structure.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.workforce-foundation.structure.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.workforce-foundation.org-chart.read','ORG_CHART: org-chart.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.workforce-foundation.org-chart.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.workforce-foundation.org-chart.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.workforce-foundation.org-chart.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.workforce-foundation.org-chart.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.catalogue.read','JOB_CATALOGUE: catalogue.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.job-architecture.catalogue.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.job-architecture.catalogue.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.catalogue.manage','JOB_CATALOGUE: catalogue.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.job-architecture.catalogue.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.catalogue.publish','JOB_CATALOGUE: catalogue.publish','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.job-architecture.catalogue.publish');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.positions.read','POSITIONS: positions.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.job-architecture.positions.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.job-architecture.positions.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.positions.request','POSITIONS: positions.request','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.job-architecture.positions.request');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.positions.approve','POSITIONS: positions.approve','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.job-architecture.positions.approve');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.position-requirements.read','POSITION_REQUIREMENTS: position-requirements.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.job-architecture.position-requirements.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.job-architecture.position-requirements.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.position-requirements.request','POSITION_REQUIREMENTS: position-requirements.request','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.job-architecture.position-requirements.request');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.job-architecture.position-requirements.waive','POSITION_REQUIREMENTS: position-requirements.waive','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.job-architecture.position-requirements.waive');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.directory.read','EMPLOYEE_DIRECTORY: directory.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.employee.directory.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.employee.directory.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.directory.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.directory.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.team.read','TEAM_DIRECTORY: team.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.employee.team.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.profile.self.read','MY_PROFILE: profile.self.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.employee.profile.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.employee.profile.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.profile.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.profile.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.profile.self.manage','MY_PROFILE: profile.self.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.employee.profile.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.employee.profile.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.profile.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.profile.self.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.records.read','EMPLOYEE_RECORDS: records.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.records.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.records.manage','EMPLOYEE_RECORDS: records.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.records.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.records.emergency.read','EMPLOYEE_RECORDS: records.emergency.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.records.emergency.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.profile-configuration.read','EMPLOYEE_PROFILE_CONFIGURATION: profile-configuration.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.profile-configuration.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.profile-configuration.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.profile-configuration.manage','EMPLOYEE_PROFILE_CONFIGURATION: profile-configuration.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.profile-configuration.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.import.read','EMPLOYEE_IMPORT: import.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.import.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.import.manage','EMPLOYEE_IMPORT: import.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.import.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.changes.read','EMPLOYMENT_CHANGES: changes.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.changes.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.changes.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.changes.request','EMPLOYMENT_CHANGES: changes.request','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.changes.request');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.changes.approve','EMPLOYMENT_CHANGES: changes.approve','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.changes.approve');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.probation.read','PROBATION_MANAGEMENT: probation.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.probation.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.probation.manage','PROBATION_MANAGEMENT: probation.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.probation.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.probation.review','PROBATION_REVIEW: probation.review','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.employee.probation.review');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.hr-service.handle','HR_SERVICE_DESK: hr-service.handle','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.hr-service.handle');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.hr-service.configure','HR_SERVICE_DESK: hr-service.configure','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.hr-service.configure');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.hr-requests.self.read','MY_HR_REQUESTS: hr-requests.self.read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.employee.hr-requests.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.employee.hr-requests.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.hr-requests.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.hr-requests.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.employee.hr-requests.self.manage','MY_HR_REQUESTS: hr-requests.self.manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.employee.hr-requests.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.employee.hr-requests.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.employee.hr-requests.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.employee.hr-requests.self.manage');
