-- Ownership: access-control. Approved HCM-1 local business grants; no fabricated audit events.
PERFORM set_config('hcm.tenant_id','local-dunder-mifflin',true);
UPDATE hcm.access_role SET system_role=true, protected_admin=(id='tenant-administrator') WHERE tenant_id='local-dunder-mifflin' AND id IN ('employee','manager','hr-specialist','tenant-administrator');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.access-control.assignments.read','ACCESS_ASSIGNMENTS: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.access-control.assignments.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.access-control.assignments.manage','ACCESS_ASSIGNMENTS: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.access-control.assignments.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.access-control.catalogue.read','APP_CATALOGUE_CONFIGURATION: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.access-control.catalogue.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.audit.events.read','AUDIT_LOG: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.audit.events.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.audit.exports.read','DATA_EXPORT_LOG: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.audit.exports.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.requests.read','DOCUMENT_REQUESTS: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.requests.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.requests.manage','DOCUMENT_REQUESTS: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.requests.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.requests.self.read','DOCUMENT_REQUESTS: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.documents.requests.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.documents.requests.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.requests.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.documents.requests.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.requests.self.submit','DOCUMENT_REQUESTS: submit','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.documents.requests.self.submit');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.documents.requests.self.submit');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.requests.self.submit');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.documents.requests.self.submit');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.requests.download','DOCUMENT_REQUESTS: download','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.requests.download');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.requests.self.download','DOCUMENT_REQUESTS: download','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.documents.requests.self.download');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.documents.requests.self.download');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.requests.self.download');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.documents.requests.self.download');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.templates.read','DOCUMENT_TEMPLATES: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.templates.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.templates.manage','DOCUMENT_TEMPLATES: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.templates.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.templates.download','DOCUMENT_TEMPLATES: download','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.templates.download');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.types.read','DOCUMENT_TYPES: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.types.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.types.manage','DOCUMENT_TYPES: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.types.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.identity-access.domains.read','DOMAIN_CONFIGURATION: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.identity-access.domains.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.worker.read','EMPLOYEE_DOCUMENTS: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.worker.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.worker.manage','EMPLOYEE_DOCUMENTS: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.worker.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.worker.download','EMPLOYEE_DOCUMENTS: download','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.worker.download');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.identity-access.accounts.read','IDENTITY_ADMINISTRATION: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.identity-access.accounts.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.identity-access.accounts.manage','IDENTITY_ADMINISTRATION: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.identity-access.accounts.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.audit.activity.self.read','MY_ACTIVITY: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.audit.activity.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.audit.activity.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.audit.activity.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.audit.activity.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.self.read','MY_DOCUMENTS: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.documents.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.documents.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.documents.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.documents.self.download','MY_DOCUMENTS: download','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.documents.self.download');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.documents.self.download');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.documents.self.download');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.documents.self.download');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.inbox.self.read','MY_NOTIFICATIONS: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.notifications.inbox.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.notifications.inbox.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.notifications.inbox.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.inbox.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.inbox.self.manage','MY_NOTIFICATIONS: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.notifications.inbox.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.notifications.inbox.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.notifications.inbox.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.inbox.self.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.preferences.self.read','MY_NOTIFICATION_PREFERENCES: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.notifications.preferences.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.notifications.preferences.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.notifications.preferences.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.preferences.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.preferences.self.manage','MY_NOTIFICATION_PREFERENCES: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.notifications.preferences.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.notifications.preferences.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.notifications.preferences.self.manage');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.preferences.self.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.identity-access.security.self.read','MY_SECURITY: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.identity-access.security.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.identity-access.security.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.identity-access.security.self.read');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.identity-access.security.self.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.rules.read','NOTIFICATION_RULES: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.rules.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.rules.manage','NOTIFICATION_RULES: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.rules.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.templates.read','NOTIFICATION_TEMPLATES: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.templates.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.notifications.templates.manage','NOTIFICATION_TEMPLATES: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.notifications.templates.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.access-control.roles.read','ROLE_MANAGEMENT: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.access-control.roles.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.access-control.roles.manage','ROLE_MANAGEMENT: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.access-control.roles.manage');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.audit.sensitive-access.read','SENSITIVE_ACCESS_LOG: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.audit.sensitive-access.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.access-control.reviews.read','TENANT_ACCESS_REVIEWS: read','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.access-control.reviews.read');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.access-control.reviews.manage','TENANT_ACCESS_REVIEWS: manage','business-operation');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.access-control.reviews.manage');
