-- Ownership: access-control. Approved fictional Dunder Mifflin development seed v1.
PERFORM set_config('hcm.tenant_id', 'local-dunder-mifflin', true);
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.access-control','access-control') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.access-control');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.analytics','analytics') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.analytics');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.assets','assets') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.assets');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.attendance','attendance') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.attendance');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.audit','audit') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.audit');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.compensation-benefits','compensation-benefits') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.compensation-benefits');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.documents','documents') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.documents');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.employee','employee') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.employee');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.engagement','engagement') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.engagement');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.expenses','expenses') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.expenses');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.governance','governance') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.governance');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.identity-access','identity-access') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.identity-access');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.job-architecture','job-architecture') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.job-architecture');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.learning','learning') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.learning');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.leave','leave') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.leave');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.notifications','notifications') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.notifications');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.offboarding','offboarding') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.offboarding');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.onboarding','onboarding') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.onboarding');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.payroll','payroll') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.payroll');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.performance','performance') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.performance');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.projects','projects') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.projects');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.recruitment','recruitment') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.recruitment');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.skills','skills') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.skills');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.timesheet','timesheet') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.timesheet');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.workflow','workflow') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.workflow');
INSERT INTO hcm.entitlement_definition (code,domain) VALUES ('hcm.workforce-foundation','workforce-foundation') ON CONFLICT (code) DO NOTHING;
INSERT INTO hcm.tenant_entitlement (tenant_id,code) VALUES ('local-dunder-mifflin','hcm.workforce-foundation');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ACCESS_ASSIGNMENTS.discover','Access Assignments','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ACTIVE_SESSIONS.discover','Active Sessions','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ALUMNI_MANAGEMENT.discover','Alumni Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ANNOUNCEMENTS.discover','Announcements','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ANNOUNCEMENT_MANAGEMENT.discover','Announcement Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.API_CREDENTIALS.discover','API Credentials','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.APPLY_LEAVE.discover','Apply Leave','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.APPROVE_ATTENDANCE.discover','Approve Attendance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.APPROVE_EXPENSES.discover','Approve Expenses','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.APPROVE_LEAVES.discover','Approve Leaves','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.APPROVE_TIMESHEETS.discover','Approve Timesheets','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.APP_CATALOGUE_CONFIGURATION.discover','App Catalogue Configuration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ASSET_ADMINISTRATION.discover','Asset Administration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ASSET_CATEGORIES.discover','Asset Categories','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ASSET_MAINTENANCE.discover','Asset Maintenance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ASSET_UTILIZATION.discover','Asset Utilization','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ASSIGN_PROJECTS.discover','Assign Projects','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ATTENDANCE_CORRECTIONS.discover','Attendance Corrections','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ATTENDANCE_MANAGEMENT.discover','Attendance Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ATTENDANCE_REPORT.discover','Attendance Report','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ATTRITION_DASHBOARD.discover','Attrition Dashboard','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.AUDIT_LOG.discover','Audit Log','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.BACKGROUND_CHECKS.discover','Background Checks','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.BENEFITS_COST_ANALYSIS.discover','Benefits Cost Analysis','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.BENEFIT_CATALOGUE.discover','Benefit Catalogue','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.BENEFIT_PROGRAMS.discover','Benefit Programs','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.CANDIDATE_PIPELINE.discover','Candidate Pipeline','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.CLIENT_MANAGEMENT.discover','Client Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMPENSATION_ANALYSIS.discover','Compensation Analysis','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMPENSATION_COMPONENTS.discover','Compensation Components','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMPENSATION_CYCLES.discover','Compensation Cycles','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMPETENCY_CATALOGUE.discover','Competency Catalogue','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMPLIANCE_DASHBOARD.discover','Compliance Dashboard','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMPLIANCE_TRACKING.discover','Compliance Tracking','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMP_OFF_ADMINISTRATION.discover','Comp Off Administration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.COMP_OFF_ENCASHMENT.discover','Comp Off Encashment','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.DATA_EXPORT_LOG.discover','Data Export Log','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.DATA_RIGHTS_REQUESTS.discover','Data Rights Requests','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.DOCUMENT_REQUESTS.discover','Document Requests','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.DOCUMENT_TEMPLATES.discover','Document Templates','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.DOCUMENT_TYPES.discover','Document Types','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.DOMAIN_CONFIGURATION.discover','Domain Configuration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMAIL_SENDER_CONFIGURATION.discover','Email Sender Configuration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMPLOYEE_DIRECTORY.discover','Employee Directory','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMPLOYEE_DOCUMENTS.discover','Employee Documents','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMPLOYEE_IMPORT.discover','Employee Import','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMPLOYEE_PROFILE_CONFIGURATION.discover','Employee Profile Configuration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMPLOYEE_RECORDS.discover','Employee Records','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMPLOYEE_REFERRALS.discover','Employee Referrals','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EMPLOYMENT_CHANGES.discover','Employment Changes','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ENGAGEMENT_SURVEYS.discover','Engagement Surveys','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EXPENSE_ADMINISTRATION.discover','Expense Administration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EXPENSE_ANALYSIS.discover','Expense Analysis','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.EXPENSE_POLICIES.discover','Expense Policies','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.FINAL_SETTLEMENTS.discover','Final Settlements','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.GIVE_FEEDBACK.discover','Give Feedback','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.GIVE_RECOGNITION.discover','Give Recognition','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.HEADCOUNT_ANALYSIS.discover','Headcount Analysis','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.HIRING_FUNNEL.discover','Hiring Funnel','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.HOLIDAY_CALENDARS.discover','Holiday Calendars','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.HR_ANALYTICS.discover','HR Analytics','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.HR_SERVICE_DESK.discover','HR Service Desk','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.IDENTIFICATION_TYPES.discover','Identification Types','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.IDENTITY_ADMINISTRATION.discover','Identity Administration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.INITIATE_PIP.discover','Initiate PIP','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.INTERVIEW_OPERATIONS.discover','Interview Operations','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.INTERVIEW_PANEL.discover','Interview Panel','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.JOB_CATALOGUE.discover','Job Catalogue','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.JOB_REQUISITIONS.discover','Job Requisitions','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LEARNING_PATHS.discover','Learning Paths','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LEARNING_PROGRAMS.discover','Learning Programs','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LEAVE_ADMINISTRATION.discover','Leave Administration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LEAVE_BALANCE.discover','Leave Balance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LEAVE_ENCASHMENT.discover','Leave Encashment','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LEAVE_POLICIES.discover','Leave Policies','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LEAVE_TRENDS.discover','Leave Trends','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.LOOKUP_VALUES.discover','Lookup Values','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_ACTIVITY.discover','My Activity','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_APPROVALS.discover','My Approvals','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_ASSETS.discover','My Assets','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_ATTENDANCE.discover','My Attendance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_BENEFITS.discover','My Benefits','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_COMPENSATION.discover','My Compensation','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_DOCUMENTS.discover','My Documents','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_EXIT.discover','My Exit','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_EXPENSES.discover','My Expenses','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_GOALS.discover','My Goals','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_HR_REQUESTS.discover','My HR Requests','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_LEARNING.discover','My Learning','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_NOTIFICATIONS.discover','My Notifications','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_NOTIFICATION_PREFERENCES.discover','My Notification Preferences','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_ONBOARDING.discover','My Onboarding','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_PAYSLIPS.discover','My Payslips','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_PERFORMANCE.discover','My Performance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_PIP.discover','My PIP','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_PROFILE.discover','My Profile','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_PROJECTS.discover','My Projects','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_SCHEDULE.discover','My Schedule','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_SECURITY.discover','My Security','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_SKILLS.discover','My Skills','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_TASKS.discover','My Tasks','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_TAX_DECLARATIONS.discover','My Tax Declarations','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_TAX_DOCUMENTS.discover','My Tax Documents','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_TIMESHEET.discover','My Timesheet','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.MY_TRAVEL_ADVANCES.discover','My Travel Advances','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.NOTIFICATION_RULES.discover','Notification Rules','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.NOTIFICATION_TEMPLATES.discover','Notification Templates','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.OFFBOARDING_OPERATIONS.discover','Offboarding Operations','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.OFFER_MANAGEMENT.discover','Offer Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ONBOARDING_METRICS.discover','Onboarding Metrics','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ONBOARDING_OPERATIONS.discover','Onboarding Operations','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ORG_CHART.discover','Org Chart','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.OUTBOUND_WEBHOOKS.discover','Outbound Webhooks','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PAYROLL_COMPLIANCE.discover','Payroll Compliance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PAYROLL_INPUTS.discover','Payroll Inputs','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PAYROLL_RUNS.discover','Payroll Runs','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PAYROLL_SUMMARY.discover','Payroll Summary','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PERFORMANCE_CYCLES.discover','Performance Cycles','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PERFORMANCE_INSIGHTS.discover','Performance Insights','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PERF_REVIEW.discover','Perf Review','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PIP_MANAGEMENT.discover','PIP Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.POLICY_ACKNOWLEDGEMENTS.discover','Policy Acknowledgements','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.POLICY_MANAGEMENT.discover','Policy Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.POSITIONS.discover','Positions','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.POSITION_REQUIREMENTS.discover','Position Requirements','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PROBATION_MANAGEMENT.discover','Probation Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PROBATION_REVIEW.discover','Probation Review','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PROJECT_DATA_IMPORT.discover','Project Data Import','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PROJECT_MANAGEMENT.discover','Project Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.PROJECT_UTILIZATION.discover','Project Utilization','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.RECOGNITION.discover','Recognition','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.RECOGNITION_PROGRAMS.discover','Recognition Programs','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.REFERENCE_LETTERS.discover','Reference Letters','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.REFERRAL_MANAGEMENT.discover','Referral Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.REIMBURSEMENT_RUNS.discover','Reimbursement Runs','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.REPORT_BUILDER.discover','Report Builder','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.RETENTION_POLICIES.discover','Retention Policies','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.ROLE_MANAGEMENT.discover','Role Management','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SALARY_REVISIONS.discover','Salary Revisions','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SECURITY_POLICIES.discover','Security Policies','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SENSITIVE_ACCESS_LOG.discover','Sensitive Access Log','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SHIFT_PLANNING.discover','Shift Planning','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SKILLS_CATALOGUE.discover','Skills Catalogue','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SKILL_GAP_REPORT.discover','Skill Gap Report','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SSO_CONFIGURATION.discover','SSO Configuration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.SURVEYS.discover','Surveys','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TASK_TEMPLATES.discover','Task Templates','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TAX_DECLARATION_ADMIN.discover','Tax Declaration Admin','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_ATTENDANCE.discover','Team Attendance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_CALENDAR.discover','Team Calendar','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_DIRECTORY.discover','Team Directory','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_EXPENSES.discover','Team Expenses','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_GOALS.discover','Team Goals','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_LEARNING.discover','Team Learning','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_OFFBOARDING.discover','Team Offboarding','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_ONBOARDING.discover','Team Onboarding','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_SKILLS.discover','Team Skills','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_TIMESHEET.discover','Team Timesheet','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TEAM_UTILIZATION.discover','Team Utilization','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TENANT_ACCESS_REVIEWS.discover','Tenant Access Reviews','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TIMESHEET_ADMINISTRATION.discover','Timesheet Administration','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TIMESHEET_COMPLIANCE.discover','Timesheet Compliance','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TIMESHEET_POLICIES.discover','Timesheet Policies','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TRAINING_EFFECTIVENESS.discover','Training Effectiveness','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.TRAVEL_ADVANCE_ADMIN.discover','Travel Advance Admin','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.UTILIZATION_POLICIES.discover','Utilization Policies','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.WORKFLOW_DEFINITIONS.discover','Workflow Definitions','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.WORKFLOW_OPERATIONS.discover','Workflow Operations','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.WORK_SCHEDULES.discover','Work Schedules','catalogue-discovery');
INSERT INTO hcm.access_permission (tenant_id,code,description,kind) VALUES ('local-dunder-mifflin','hcm.catalogue.WORK_SCHEDULE_TEMPLATES.discover','Work Schedule Templates','catalogue-discovery');
INSERT INTO hcm.access_role (tenant_id,id,label) VALUES ('local-dunder-mifflin','employee','Employee');
INSERT INTO hcm.account_role (tenant_id,account_id,role_id) VALUES ('local-dunder-mifflin','dunder-mifflin/account/jim','employee');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.ANNOUNCEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.APPLY_LEAVE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.ATTENDANCE_CORRECTIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.COMP_OFF_ENCASHMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.EMPLOYEE_DIRECTORY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.EMPLOYEE_REFERRALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.GIVE_FEEDBACK.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.LEAVE_BALANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_ACTIVITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_ASSETS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_ATTENDANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_BENEFITS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_COMPENSATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_EXIT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_EXPENSES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_GOALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_HR_REQUESTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_LEARNING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_NOTIFICATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_NOTIFICATION_PREFERENCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_ONBOARDING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_PAYSLIPS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_PERFORMANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_PIP.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_PROFILE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_PROJECTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_SCHEDULE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_SECURITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_SKILLS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_TASKS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_TAX_DECLARATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_TAX_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_TIMESHEET.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.MY_TRAVEL_ADVANCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.ORG_CHART.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.POLICY_ACKNOWLEDGEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.RECOGNITION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','employee','hcm.catalogue.SURVEYS.discover');
INSERT INTO hcm.access_role (tenant_id,id,label) VALUES ('local-dunder-mifflin','manager','Manager');
INSERT INTO hcm.account_role (tenant_id,account_id,role_id) VALUES ('local-dunder-mifflin','dunder-mifflin/account/michael','manager');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.ANNOUNCEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.APPLY_LEAVE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.APPROVE_ATTENDANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.APPROVE_EXPENSES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.APPROVE_LEAVES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.APPROVE_TIMESHEETS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.ASSIGN_PROJECTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.ATTENDANCE_CORRECTIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.COMP_OFF_ENCASHMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.EMPLOYEE_DIRECTORY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.EMPLOYEE_REFERRALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.GIVE_FEEDBACK.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.GIVE_RECOGNITION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.INITIATE_PIP.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.INTERVIEW_PANEL.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.LEAVE_BALANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_ACTIVITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_APPROVALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_ASSETS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_ATTENDANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_BENEFITS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_COMPENSATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_EXIT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_EXPENSES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_GOALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_HR_REQUESTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_LEARNING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_NOTIFICATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_NOTIFICATION_PREFERENCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_ONBOARDING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_PAYSLIPS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_PERFORMANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_PIP.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_PROFILE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_PROJECTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_SCHEDULE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_SECURITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_SKILLS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_TASKS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_TAX_DECLARATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_TAX_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_TIMESHEET.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.MY_TRAVEL_ADVANCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.ORG_CHART.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.PERF_REVIEW.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.POLICY_ACKNOWLEDGEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.PROBATION_REVIEW.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.RECOGNITION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.SHIFT_PLANNING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.SURVEYS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_ATTENDANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_CALENDAR.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_DIRECTORY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_EXPENSES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_GOALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_LEARNING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_OFFBOARDING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_ONBOARDING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_SKILLS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_TIMESHEET.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','manager','hcm.catalogue.TEAM_UTILIZATION.discover');
INSERT INTO hcm.access_role (tenant_id,id,label) VALUES ('local-dunder-mifflin','hr-specialist','HR Operations');
INSERT INTO hcm.account_role (tenant_id,account_id,role_id) VALUES ('local-dunder-mifflin','dunder-mifflin/account/toby','hr-specialist');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ALUMNI_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ANNOUNCEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ANNOUNCEMENT_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.APPLY_LEAVE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ASSET_ADMINISTRATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ASSET_MAINTENANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ATTENDANCE_CORRECTIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ATTENDANCE_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.BACKGROUND_CHECKS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.BENEFIT_PROGRAMS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.CANDIDATE_PIPELINE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.CLIENT_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.COMPENSATION_CYCLES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.COMPETENCY_CATALOGUE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.COMPLIANCE_TRACKING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.COMP_OFF_ADMINISTRATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.COMP_OFF_ENCASHMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.DOCUMENT_REQUESTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EMPLOYEE_DIRECTORY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EMPLOYEE_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EMPLOYEE_IMPORT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EMPLOYEE_PROFILE_CONFIGURATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EMPLOYEE_RECORDS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EMPLOYEE_REFERRALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EMPLOYMENT_CHANGES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ENGAGEMENT_SURVEYS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.EXPENSE_ADMINISTRATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.FINAL_SETTLEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.GIVE_FEEDBACK.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.HOLIDAY_CALENDARS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.HR_SERVICE_DESK.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.INTERVIEW_OPERATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.JOB_REQUISITIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.LEARNING_PATHS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.LEARNING_PROGRAMS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.LEAVE_ADMINISTRATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.LEAVE_BALANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.LEAVE_ENCASHMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.LEAVE_POLICIES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_ACTIVITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_ASSETS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_ATTENDANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_BENEFITS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_COMPENSATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_EXIT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_EXPENSES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_GOALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_HR_REQUESTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_LEARNING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_NOTIFICATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_NOTIFICATION_PREFERENCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_ONBOARDING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_PAYSLIPS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_PERFORMANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_PIP.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_PROFILE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_PROJECTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_SCHEDULE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_SECURITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_SKILLS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_TASKS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_TAX_DECLARATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_TAX_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_TIMESHEET.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.MY_TRAVEL_ADVANCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.OFFBOARDING_OPERATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.OFFER_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ONBOARDING_OPERATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.ORG_CHART.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PAYROLL_COMPLIANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PAYROLL_INPUTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PAYROLL_RUNS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PERFORMANCE_CYCLES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PIP_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.POLICY_ACKNOWLEDGEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.POLICY_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.POSITIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PROBATION_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PROJECT_DATA_IMPORT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.PROJECT_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.RECOGNITION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.RECOGNITION_PROGRAMS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.REFERENCE_LETTERS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.REFERRAL_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.REIMBURSEMENT_RUNS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.SALARY_REVISIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.SKILLS_CATALOGUE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.SURVEYS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.TAX_DECLARATION_ADMIN.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.TIMESHEET_ADMINISTRATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.TRAVEL_ADVANCE_ADMIN.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.UTILIZATION_POLICIES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.WORKFLOW_OPERATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','hr-specialist','hcm.catalogue.WORK_SCHEDULES.discover');
INSERT INTO hcm.access_role (tenant_id,id,label) VALUES ('local-dunder-mifflin','tenant-administrator','Tenant Administrator');
INSERT INTO hcm.account_role (tenant_id,account_id,role_id) VALUES ('local-dunder-mifflin','dunder-mifflin/account/david','tenant-administrator');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.ACCESS_ASSIGNMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.ACTIVE_SESSIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.ANNOUNCEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.API_CREDENTIALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.APPLY_LEAVE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.APP_CATALOGUE_CONFIGURATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.ASSET_CATEGORIES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.ATTENDANCE_CORRECTIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.AUDIT_LOG.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.BENEFIT_CATALOGUE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.COMPENSATION_COMPONENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.COMP_OFF_ENCASHMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.DATA_EXPORT_LOG.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.DATA_RIGHTS_REQUESTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.DOCUMENT_TEMPLATES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.DOCUMENT_TYPES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.DOMAIN_CONFIGURATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.EMAIL_SENDER_CONFIGURATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.EMPLOYEE_DIRECTORY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.EMPLOYEE_REFERRALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.EXPENSE_POLICIES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.GIVE_FEEDBACK.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.IDENTIFICATION_TYPES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.IDENTITY_ADMINISTRATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.JOB_CATALOGUE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.LEAVE_BALANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.LOOKUP_VALUES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_ACTIVITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_ASSETS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_ATTENDANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_BENEFITS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_COMPENSATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_EXIT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_EXPENSES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_GOALS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_HR_REQUESTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_LEARNING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_NOTIFICATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_NOTIFICATION_PREFERENCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_ONBOARDING.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_PAYSLIPS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_PERFORMANCE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_PIP.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_PROFILE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_PROJECTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_SCHEDULE.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_SECURITY.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_SKILLS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_TASKS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_TAX_DECLARATIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_TAX_DOCUMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_TIMESHEET.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.MY_TRAVEL_ADVANCES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.NOTIFICATION_RULES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.NOTIFICATION_TEMPLATES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.ORG_CHART.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.OUTBOUND_WEBHOOKS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.POLICY_ACKNOWLEDGEMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.POSITION_REQUIREMENTS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.RECOGNITION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.RETENTION_POLICIES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.ROLE_MANAGEMENT.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.SECURITY_POLICIES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.SENSITIVE_ACCESS_LOG.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.SSO_CONFIGURATION.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.SURVEYS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.TASK_TEMPLATES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.TENANT_ACCESS_REVIEWS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.TIMESHEET_POLICIES.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.WORKFLOW_DEFINITIONS.discover');
INSERT INTO hcm.role_permission (tenant_id,role_id,permission_code) VALUES ('local-dunder-mifflin','tenant-administrator','hcm.catalogue.WORK_SCHEDULE_TEMPLATES.discover');
