import './global.css'

export const metadata = {
	title: 'Welcome to marketing-web',
	description: 'Generated by create-nx-workspace',
}

/** Wrap every marketing route in the shared English-language HTML document and body. */
export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
